import type { GovService } from "./services-data";

// Common helper documents shared by most state welfare schemes
const baseDocs = [
  { title: { en: "Aadhaar Card", hi: "आधार कार्ड" }, required: true },
  { title: { en: "Domicile / Residence proof of the state", hi: "राज्य का निवास प्रमाण" }, required: true },
  { title: { en: "Bank account passbook (Aadhaar-linked)", hi: "बैंक पासबुक (आधार-लिंक्ड)" }, required: true },
  { title: { en: "Passport-size photograph", hi: "पासपोर्ट साइज़ फोटो" }, required: true },
];

export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa",
  "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala",
  "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland",
  "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman & Nicobar Islands", "Chandigarh", "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi", "Jammu & Kashmir", "Ladakh", "Lakshadweep", "Puducherry",
] as const;

export const stateServices: GovService[] = [
  {
    slug: "ap-ysr-rythu-bharosa",
    name: { en: "YSR Rythu Bharosa – PM Kisan", hi: "वाईएसआर रायतु भरोसा" },
    category: "Welfare",
    authority: "Andhra Pradesh Agriculture Department",
    state: "Andhra Pradesh",
    processingTime: "30–60 days",
    fee: "Free",
    description: {
      en: "Annual financial assistance of ₹13,500 to eligible farmer families in Andhra Pradesh.",
      hi: "आंध्र प्रदेश के पात्र किसान परिवारों को सालाना ₹13,500 की वित्तीय सहायता।",
    },
    documents: [
      ...baseDocs,
      { title: { en: "Land ownership / pattadar passbook", hi: "भूमि स्वामित्व / पट्टादार पासबुक" }, required: true },
    ],
    eligibility: {
      en: ["Resident farmer family of Andhra Pradesh", "Holding cultivable land or eligible tenant farmer"],
      hi: ["आंध्र प्रदेश का किसान परिवार", "खेती योग्य भूमि वाला या पात्र काश्तकार"],
    },
    applyUrl: "https://ysrrythubharosa.ap.gov.in",
  },
  {
    slug: "ar-cmaay",
    name: { en: "CM Arogya Arunachal Yojana (CMAAY)", hi: "सीएम आरोग्य अरुणाचल योजना" },
    category: "Welfare",
    authority: "Arunachal Pradesh Health Department",
    state: "Arunachal Pradesh",
    processingTime: "15–30 days",
    fee: "Free",
    description: {
      en: "Cashless health coverage up to ₹5 lakh per family per year for residents of Arunachal Pradesh.",
      hi: "अरुणाचल प्रदेश के निवासियों को प्रति परिवार सालाना ₹5 लाख तक का कैशलेस स्वास्थ्य कवर।",
    },
    documents: [...baseDocs, { title: { en: "APST / Permanent Resident Certificate", hi: "स्थायी निवास प्रमाण" }, required: true }],
    eligibility: { en: ["Permanent resident of Arunachal Pradesh"], hi: ["अरुणाचल प्रदेश का स्थायी निवासी"] },
    applyUrl: "https://cmaay.com",
  },
  {
    slug: "as-orunodoi",
    name: { en: "Orunodoi Scheme", hi: "ओरुनोदोई योजना" },
    category: "Welfare",
    authority: "Assam Finance Department",
    state: "Assam",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "₹1,250 per month direct transfer to women heads of economically weaker families in Assam.",
      hi: "असम की आर्थिक रूप से कमज़ोर महिलाओं को प्रति माह ₹1,250 का सीधा हस्तांतरण।",
    },
    documents: [...baseDocs, { title: { en: "Ration card / BPL certificate", hi: "राशन कार्ड / बीपीएल प्रमाण" }, required: true }],
    eligibility: { en: ["Woman head of family", "Annual income below ₹2 lakh"], hi: ["परिवार की महिला मुखिया", "वार्षिक आय ₹2 लाख से कम"] },
    applyUrl: "https://orunodoi.assam.gov.in",
  },
  {
    slug: "br-kanya-utthan",
    name: { en: "Mukhyamantri Kanya Utthan Yojana", hi: "मुख्यमंत्री कन्या उत्थान योजना" },
    category: "Welfare",
    authority: "Bihar Social Welfare Department",
    state: "Bihar",
    processingTime: "30–45 days",
    fee: "Free",
    description: {
      en: "Financial assistance up to ₹50,000 to girls in Bihar from birth through graduation.",
      hi: "बिहार की बेटियों को जन्म से स्नातक तक ₹50,000 तक की वित्तीय सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Birth certificate / School certificate", hi: "जन्म / स्कूल प्रमाणपत्र" }, required: true }],
    eligibility: { en: ["Girl child resident of Bihar", "Studying in recognised institution at applicable stages"], hi: ["बिहार की बालिका"] },
    applyUrl: "https://medhasoft.bih.nic.in",
  },
  {
    slug: "cg-rajiv-gandhi-kisan-nyay",
    name: { en: "Rajiv Gandhi Kisan Nyay Yojana", hi: "राजीव गांधी किसान न्याय योजना" },
    category: "Welfare",
    authority: "Chhattisgarh Agriculture Department",
    state: "Chhattisgarh",
    processingTime: "Seasonal",
    fee: "Free",
    description: {
      en: "Input subsidy to paddy and other crop growers of Chhattisgarh, credited directly to farmer accounts.",
      hi: "छत्तीसगढ़ के धान और अन्य फसल उत्पादक किसानों के खातों में सीधे इनपुट सब्सिडी।",
    },
    documents: [...baseDocs, { title: { en: "Land records / Kisan registration", hi: "भू-अभिलेख / किसान पंजीयन" }, required: true }],
    eligibility: { en: ["Registered farmer of Chhattisgarh selling at procurement centres"], hi: ["छत्तीसगढ़ के पंजीकृत किसान"] },
    applyUrl: "https://rgkny.cg.nic.in",
  },
  {
    slug: "ga-griha-aadhar",
    name: { en: "Griha Aadhar Scheme", hi: "गृह आधार योजना" },
    category: "Welfare",
    authority: "Goa Directorate of Women & Child Development",
    state: "Goa",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Monthly financial assistance to housewives in Goa to offset rising household expenses.",
      hi: "गोवा की गृहिणियों को घरेलू खर्च के लिए मासिक वित्तीय सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Marriage certificate", hi: "विवाह प्रमाणपत्र" }, required: false }],
    eligibility: { en: ["Married woman resident of Goa for 15+ years", "Family income within prescribed limit"], hi: ["गोवा की 15+ वर्ष की निवासी विवाहित महिला"] },
    applyUrl: "https://wcd.goa.gov.in",
  },
  {
    slug: "gj-ma-yojana",
    name: { en: "Mukhyamantri Amrutum (MA) Yojana", hi: "मुख्यमंत्री अमृतम योजना" },
    category: "Welfare",
    authority: "Gujarat Health & Family Welfare",
    state: "Gujarat",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Cashless tertiary care up to ₹10 lakh per family per year for low-income residents of Gujarat.",
      hi: "गुजरात के कम आय वाले परिवारों को सालाना ₹10 लाख तक का कैशलेस इलाज।",
    },
    documents: [...baseDocs, { title: { en: "Income certificate (below ₹4 lakh)", hi: "आय प्रमाणपत्र" }, required: true }],
    eligibility: { en: ["Family income up to ₹4 lakh per annum", "Resident of Gujarat"], hi: ["गुजरात निवासी"] },
    applyUrl: "https://magujarat.com",
  },
  {
    slug: "hr-parivar-pehchan-patra",
    name: { en: "Parivar Pehchan Patra (PPP)", hi: "परिवार पहचान पत्र" },
    category: "Identity",
    authority: "Haryana Citizen Resources Information Department",
    state: "Haryana",
    processingTime: "15–30 days",
    fee: "Free",
    description: {
      en: "8-digit family ID linking all Haryana residents to a single verified family record for state schemes.",
      hi: "हरियाणा निवासियों के लिए राज्य योजनाओं हेतु 8-अंकीय परिवार पहचान पत्र।",
    },
    documents: [...baseDocs],
    eligibility: { en: ["All families residing in Haryana"], hi: ["हरियाणा में निवास करने वाले सभी परिवार"] },
    applyUrl: "https://meraparivar.haryana.gov.in",
  },
  {
    slug: "hp-grihini-suvidha",
    name: { en: "Himachal Grihini Suvidha Yojana", hi: "हिमाचल गृहिणी सुविधा योजना" },
    category: "Welfare",
    authority: "Himachal Pradesh Food & Civil Supplies",
    state: "Himachal Pradesh",
    processingTime: "15 days",
    fee: "Free LPG connection",
    description: {
      en: "Free LPG connection with stove and first refill to families in Himachal Pradesh not covered under PMUY.",
      hi: "हिमाचल प्रदेश के परिवारों को नि:शुल्क एलपीजी कनेक्शन।",
    },
    documents: [...baseDocs, { title: { en: "Ration card", hi: "राशन कार्ड" }, required: true }],
    eligibility: { en: ["Resident family of HP without an existing LPG connection"], hi: ["एलपीजी कनेक्शन रहित HP परिवार"] },
    applyUrl: "https://himachal.nic.in",
  },
  {
    slug: "jh-maiya-samman",
    name: { en: "Mukhyamantri Maiya Samman Yojana", hi: "मुख्यमंत्री मईयां सम्मान योजना" },
    category: "Welfare",
    authority: "Jharkhand Women & Child Development",
    state: "Jharkhand",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Monthly cash transfer to eligible women aged 18–50 years in Jharkhand.",
      hi: "झारखंड की 18–50 वर्ष की पात्र महिलाओं को मासिक नकद हस्तांतरण।",
    },
    documents: [...baseDocs, { title: { en: "Green / pink / yellow ration card", hi: "राशन कार्ड" }, required: true }],
    eligibility: { en: ["Woman aged 18–50 years", "Resident of Jharkhand"], hi: ["झारखंड की 18–50 वर्ष की महिला"] },
    applyUrl: "https://mmmsy.jharkhand.gov.in",
  },
  {
    slug: "ka-gruha-lakshmi",
    name: { en: "Gruha Lakshmi Scheme", hi: "गृह लक्ष्मी योजना" },
    category: "Welfare",
    authority: "Karnataka Women & Child Development",
    state: "Karnataka",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "₹2,000 monthly assistance to women heads of household in Karnataka.",
      hi: "कर्नाटक की महिला गृहप्रमुखों को ₹2,000 मासिक सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Ration card showing applicant as head", hi: "मुखिया दर्शाने वाला राशन कार्ड" }, required: true }],
    eligibility: { en: ["Woman head of family in Karnataka", "Not an income-tax or GST payer"], hi: ["कर्नाटक की महिला गृहप्रमुख"] },
    applyUrl: "https://sevasindhuservices.karnataka.gov.in",
  },
  {
    slug: "kl-karunya-health",
    name: { en: "Karunya Health Scheme", hi: "करुण्य स्वास्थ्य योजना" },
    category: "Welfare",
    authority: "Kerala Social Security Mission",
    state: "Kerala",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Financial assistance for treatment of critical illnesses to BPL families in Kerala.",
      hi: "केरल के बीपीएल परिवारों को गंभीर बीमारियों के इलाज हेतु आर्थिक सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Income certificate (BPL)", hi: "आय प्रमाण (बीपीएल)" }, required: true }, { title: { en: "Treatment estimate from hospital", hi: "अस्पताल का अनुमान" }, required: true }],
    eligibility: { en: ["BPL family of Kerala", "Suffering from listed critical illness"], hi: ["केरल का बीपीएल परिवार"] },
    applyUrl: "https://socialsecuritymission.gov.in",
  },
  {
    slug: "mp-ladli-behna",
    name: { en: "Ladli Behna Yojana", hi: "लाडली बहना योजना" },
    category: "Welfare",
    authority: "Madhya Pradesh Women & Child Development",
    state: "Madhya Pradesh",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "₹1,250+ monthly assistance to eligible women in Madhya Pradesh for economic self-reliance.",
      hi: "मध्य प्रदेश की पात्र महिलाओं को आर्थिक आत्मनिर्भरता हेतु मासिक सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Samagra ID", hi: "समग्र आईडी" }, required: true }],
    eligibility: { en: ["Woman aged 21–60", "Resident of MP", "Family income < ₹2.5 lakh"], hi: ["21–60 वर्ष की MP निवासी महिला"] },
    applyUrl: "https://cmladlibahna.mp.gov.in",
  },
  {
    slug: "mh-jyotirao-phule-arogya",
    name: { en: "Mahatma Jyotirao Phule Jan Arogya Yojana", hi: "महात्मा ज्योतिराव फुले जन आरोग्य योजना" },
    category: "Welfare",
    authority: "Maharashtra Public Health Department",
    state: "Maharashtra",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Cashless hospitalisation cover up to ₹5 lakh per family per year for residents of Maharashtra.",
      hi: "महाराष्ट्र निवासियों को प्रति परिवार सालाना ₹5 लाख तक का कैशलेस इलाज।",
    },
    documents: [...baseDocs, { title: { en: "Yellow / orange / saffron ration card", hi: "राशन कार्ड" }, required: true }],
    eligibility: { en: ["Resident family of Maharashtra in eligible category"], hi: ["महाराष्ट्र निवासी परिवार"] },
    applyUrl: "https://www.jeevandayee.gov.in",
  },
  {
    slug: "mn-cm-hakshelgi-tengbang",
    name: { en: "CM-gi Hakshelgi Tengbang (CMHT)", hi: "सीएम-गी हक्शेलगी टेंगबांग" },
    category: "Welfare",
    authority: "Manipur Health Department",
    state: "Manipur",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Free quality healthcare up to ₹2 lakh per family per year for the people of Manipur.",
      hi: "मणिपुर के लोगों को प्रति परिवार सालाना ₹2 लाख तक का नि:शुल्क इलाज।",
    },
    documents: [...baseDocs, { title: { en: "Income certificate", hi: "आय प्रमाण" }, required: true }],
    eligibility: { en: ["Resident of Manipur in eligible income bracket"], hi: ["मणिपुर के पात्र निवासी"] },
    applyUrl: "https://cmht.mn.gov.in",
  },
  {
    slug: "ml-megha-health-insurance",
    name: { en: "Megha Health Insurance Scheme (MHIS)", hi: "मेघा स्वास्थ्य बीमा योजना" },
    category: "Welfare",
    authority: "Meghalaya Health Department",
    state: "Meghalaya",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Cashless health insurance up to ₹5.3 lakh per family per year for all residents of Meghalaya.",
      hi: "मेघालय के सभी निवासियों को प्रति परिवार सालाना ₹5.3 लाख तक का कैशलेस बीमा।",
    },
    documents: [...baseDocs],
    eligibility: { en: ["All families residing in Meghalaya"], hi: ["मेघालय के सभी परिवार"] },
    applyUrl: "https://mhis.org.in",
  },
  {
    slug: "mz-sedp",
    name: { en: "Socio-Economic Development Policy (SEDP)", hi: "सामाजिक-आर्थिक विकास नीति" },
    category: "Welfare",
    authority: "Mizoram Planning Department",
    state: "Mizoram",
    processingTime: "60 days",
    fee: "Free",
    description: {
      en: "Sectoral support for sustainable livelihoods, entrepreneurship, and skill development in Mizoram.",
      hi: "मिज़ोरम में सतत आजीविका और उद्यमिता के लिए क्षेत्रीय सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Project proposal / trade details", hi: "परियोजना प्रस्ताव" }, required: true }],
    eligibility: { en: ["Resident of Mizoram engaged in eligible livelihood activity"], hi: ["मिज़ोरम का निवासी"] },
    applyUrl: "https://sedp.mizoram.gov.in",
  },
  {
    slug: "nl-cmhis",
    name: { en: "CM's Health Insurance Scheme (CMHIS)", hi: "मुख्यमंत्री स्वास्थ्य बीमा योजना" },
    category: "Welfare",
    authority: "Nagaland Health & Family Welfare",
    state: "Nagaland",
    processingTime: "20 days",
    fee: "Free / subsidised",
    description: {
      en: "Health cover up to ₹5 lakh per family per year for state government employees and other residents of Nagaland.",
      hi: "नागालैंड के राज्य कर्मचारियों और निवासियों को सालाना ₹5 लाख तक का स्वास्थ्य कवर।",
    },
    documents: [...baseDocs, { title: { en: "Indigenous Inhabitant Certificate", hi: "स्थानीय निवास प्रमाण" }, required: true }],
    eligibility: { en: ["Indigenous resident of Nagaland or state employee"], hi: ["नागालैंड का स्थानीय निवासी"] },
    applyUrl: "https://cmhisnagaland.com",
  },
  {
    slug: "od-biju-swasthya-kalyan",
    name: { en: "Biju Swasthya Kalyan Yojana (BSKY)", hi: "बीजू स्वास्थ्य कल्याण योजना" },
    category: "Welfare",
    authority: "Odisha Health & Family Welfare",
    state: "Odisha",
    processingTime: "Immediate at empanelled hospitals",
    fee: "Free",
    description: {
      en: "Free healthcare at all state-run facilities and cashless treatment up to ₹5 lakh (₹10 lakh for women) for Odisha residents.",
      hi: "ओडिशा के निवासियों को सरकारी अस्पतालों में नि:शुल्क इलाज।",
    },
    documents: [...baseDocs, { title: { en: "BSKY card / ration card", hi: "बीएसकेवाई कार्ड" }, required: false }],
    eligibility: { en: ["All residents of Odisha for state-run facility care", "Cashless cover for eligible families"], hi: ["ओडिशा निवासी"] },
    applyUrl: "https://bsky.odisha.gov.in",
  },
  {
    slug: "pb-aam-aadmi-clinic",
    name: { en: "Aam Aadmi Clinic", hi: "आम आदमी क्लिनिक" },
    category: "Welfare",
    authority: "Punjab Health & Family Welfare",
    state: "Punjab",
    processingTime: "Walk-in",
    fee: "Free OPD & tests",
    description: {
      en: "Neighbourhood clinics offering free OPD consultation, essential medicines and diagnostic tests across Punjab.",
      hi: "पंजाब में नि:शुल्क ओपीडी, दवाएं और जांच प्रदान करने वाले क्लिनिक।",
    },
    documents: [{ title: { en: "Any government-issued ID", hi: "कोई भी सरकारी पहचान" }, required: false }],
    eligibility: { en: ["Open to all residents and visitors in Punjab"], hi: ["सभी के लिए खुला"] },
    applyUrl: "https://punjab.gov.in",
  },
  {
    slug: "rj-chiranjeevi",
    name: { en: "Chiranjeevi Swasthya Bima Yojana", hi: "चिरंजीवी स्वास्थ्य बीमा योजना" },
    category: "Welfare",
    authority: "Rajasthan Health Department",
    state: "Rajasthan",
    processingTime: "15 days",
    fee: "₹850/year (or free for eligible)",
    description: {
      en: "Cashless health insurance up to ₹25 lakh per family per year for residents of Rajasthan.",
      hi: "राजस्थान निवासियों को प्रति परिवार सालाना ₹25 लाख तक का कैशलेस बीमा।",
    },
    documents: [...baseDocs, { title: { en: "Jan Aadhaar card", hi: "जन आधार कार्ड" }, required: true }],
    eligibility: { en: ["Resident of Rajasthan with Jan Aadhaar"], hi: ["जन आधार वाले राजस्थान निवासी"] },
    applyUrl: "https://chiranjeevi.rajasthan.gov.in",
  },
  {
    slug: "sk-aama-yojana",
    name: { en: "Aama (Mother) Yojana", hi: "आमा योजना" },
    category: "Welfare",
    authority: "Sikkim Human Resource Development",
    state: "Sikkim",
    processingTime: "Per academic year",
    fee: "Free",
    description: {
      en: "Annual financial assistance to mothers whose children study in government schools in Sikkim.",
      hi: "सिक्किम के सरकारी स्कूलों में पढ़ने वाले बच्चों की माताओं को वार्षिक सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Child's school certificate", hi: "बच्चे का स्कूल प्रमाणपत्र" }, required: true }],
    eligibility: { en: ["Mother of a student enrolled in a Sikkim government school"], hi: ["सरकारी स्कूल छात्र की माता"] },
    applyUrl: "https://sikkimhrdd.org",
  },
  {
    slug: "tn-kalaignar-magalir-urimai",
    name: { en: "Kalaignar Magalir Urimai Thogai", hi: "कलैगनर मगलिर उरिमई तोगई" },
    category: "Welfare",
    authority: "Tamil Nadu Social Welfare Department",
    state: "Tamil Nadu",
    processingTime: "30–45 days",
    fee: "Free",
    description: {
      en: "₹1,000 monthly basic-income entitlement for eligible women heads of household in Tamil Nadu.",
      hi: "तमिलनाडु की पात्र महिला गृहप्रमुखों को ₹1,000 मासिक।",
    },
    documents: [...baseDocs, { title: { en: "Family card", hi: "परिवार कार्ड" }, required: true }],
    eligibility: { en: ["Woman head of family", "Resident of Tamil Nadu meeting eligibility norms"], hi: ["तमिलनाडु की महिला गृहप्रमुख"] },
    applyUrl: "https://kmut.tn.gov.in",
  },
  {
    slug: "tg-rythu-bandhu",
    name: { en: "Rythu Bandhu Scheme", hi: "रायतु बंधु योजना" },
    category: "Welfare",
    authority: "Telangana Agriculture Department",
    state: "Telangana",
    processingTime: "Each crop season",
    fee: "Free",
    description: {
      en: "Investment support of ₹5,000 per acre per season to farmers in Telangana for crop inputs.",
      hi: "तेलंगाना के किसानों को प्रति एकड़ प्रति सीज़न ₹5,000 की निवेश सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Pattadar passbook", hi: "पट्टादार पासबुक" }, required: true }],
    eligibility: { en: ["Landholding farmer in Telangana with valid pattadar passbook"], hi: ["तेलंगाना का भू-स्वामी किसान"] },
    applyUrl: "https://rythubandhu.telangana.gov.in",
  },
  {
    slug: "tr-mukhyamantri-jan-arogya",
    name: { en: "Mukhyamantri Jan Arogya Yojana (Tripura)", hi: "मुख्यमंत्री जन आरोग्य योजना (त्रिपुरा)" },
    category: "Welfare",
    authority: "Tripura Health Department",
    state: "Tripura",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Cashless health coverage extending PM-JAY benefits to additional families in Tripura.",
      hi: "त्रिपुरा में अतिरिक्त परिवारों को पीएम-जय जैसी कैशलेस कवरेज।",
    },
    documents: [...baseDocs, { title: { en: "Income / ration certificate", hi: "आय / राशन प्रमाण" }, required: true }],
    eligibility: { en: ["Resident family of Tripura not covered under PM-JAY"], hi: ["पीएम-जय से बाहर त्रिपुरा परिवार"] },
    applyUrl: "https://health.tripura.gov.in",
  },
  {
    slug: "up-kanya-sumangala",
    name: { en: "Kanya Sumangala Yojana", hi: "कन्या सुमंगला योजना" },
    category: "Welfare",
    authority: "Uttar Pradesh Women Welfare Department",
    state: "Uttar Pradesh",
    processingTime: "30–60 days",
    fee: "Free",
    description: {
      en: "Staged financial assistance up to ₹25,000 to girl children of Uttar Pradesh from birth through graduation.",
      hi: "उत्तर प्रदेश की बेटियों को जन्म से स्नातक तक ₹25,000 तक की सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Birth certificate of girl", hi: "बालिका का जन्म प्रमाण" }, required: true }],
    eligibility: { en: ["Girl child resident of UP", "Family income ≤ ₹3 lakh", "Max two girls per family"], hi: ["यूपी की बालिका, आय ≤ ₹3 लाख"] },
    applyUrl: "https://mksy.up.gov.in",
  },
  {
    slug: "uk-vatsalya-yojana",
    name: { en: "Mukhyamantri Vatsalya Yojana", hi: "मुख्यमंत्री वात्सल्य योजना" },
    category: "Welfare",
    authority: "Uttarakhand Women Empowerment & Child Development",
    state: "Uttarakhand",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Monthly assistance, education and healthcare support to children in Uttarakhand who lost parents during the pandemic.",
      hi: "उत्तराखंड के अनाथ बच्चों को मासिक सहायता, शिक्षा एवं स्वास्थ्य सहयोग।",
    },
    documents: [...baseDocs, { title: { en: "Death certificate(s) of parent(s)", hi: "माता/पिता का मृत्यु प्रमाण" }, required: true }],
    eligibility: { en: ["Child resident of Uttarakhand who lost parent(s) to COVID-19 or otherwise eligible"], hi: ["उत्तराखंड का अनाथ बच्चा"] },
    applyUrl: "https://wecd.uk.gov.in",
  },
  {
    slug: "wb-lakshmir-bhandar",
    name: { en: "Lakshmir Bhandar Scheme", hi: "लक्ष्मीर भंडार योजना" },
    category: "Welfare",
    authority: "West Bengal Women & Child Development",
    state: "West Bengal",
    processingTime: "Duare Sarkar camps",
    fee: "Free",
    description: {
      en: "Monthly basic-income support of ₹1,000 (₹1,200 for SC/ST) to women heads of households in West Bengal.",
      hi: "पश्चिम बंगाल की महिला गृहप्रमुखों को मासिक आय सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Swasthya Sathi card", hi: "स्वास्थ्य साथी कार्ड" }, required: true }],
    eligibility: { en: ["Woman aged 25–60", "Resident of West Bengal", "Not a government employee"], hi: ["पश्चिम बंगाल की 25–60 वर्ष की महिला"] },
    applyUrl: "https://socialsecurity.wb.gov.in",
  },
  {
    slug: "an-bulk-lpg-subsidy",
    name: { en: "Bulk LPG Subsidy (A&N)", hi: "बल्क एलपीजी सब्सिडी" },
    category: "Welfare",
    authority: "A&N Civil Supplies & Consumer Affairs",
    state: "Andaman & Nicobar Islands",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Subsidy on LPG cylinders for residents of Andaman & Nicobar Islands to offset higher freight costs.",
      hi: "अंडमान निकोबार निवासियों को एलपीजी पर सब्सिडी।",
    },
    documents: [...baseDocs, { title: { en: "Active LPG consumer number", hi: "सक्रिय एलपीजी उपभोक्ता नंबर" }, required: true }],
    eligibility: { en: ["Domestic LPG consumer in A&N Islands"], hi: ["अंडमान का घरेलू एलपीजी उपभोक्ता"] },
    applyUrl: "https://andaman.gov.in",
  },
  {
    slug: "ch-ladli-scheme",
    name: { en: "Ladli Scheme (Chandigarh)", hi: "लाडली योजना (चंडीगढ़)" },
    category: "Welfare",
    authority: "Chandigarh Social Welfare Department",
    state: "Chandigarh",
    processingTime: "60 days",
    fee: "Free",
    description: {
      en: "Fixed deposit of ₹20,000 in name of girl child born to residents of Chandigarh, maturing at age 18.",
      hi: "चंडीगढ़ निवासियों की बेटियों के नाम ₹20,000 की FD, 18 वर्ष पर परिपक्व।",
    },
    documents: [...baseDocs, { title: { en: "Girl's birth certificate", hi: "बालिका का जन्म प्रमाण" }, required: true }],
    eligibility: { en: ["Girl child born to Chandigarh resident", "Birth registered in UT"], hi: ["चंडीगढ़ निवासी की बालिका"] },
    applyUrl: "https://chandigarh.gov.in",
  },
  {
    slug: "dd-bal-ashirwad",
    name: { en: "Mukhyamantri Bal Ashirwad Yojana", hi: "मुख्यमंत्री बाल आशीर्वाद योजना" },
    category: "Welfare",
    authority: "DNH&DD Social Welfare",
    state: "Dadra & Nagar Haveli and Daman & Diu",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Monthly maintenance and education support to orphaned and destitute children in the UT.",
      hi: "केंद्रशासित प्रदेश के अनाथ बच्चों को मासिक भरण-पोषण एवं शिक्षा सहायता।",
    },
    documents: [...baseDocs, { title: { en: "Parent's death / destitution certificate", hi: "मृत्यु / निराश्रित प्रमाण" }, required: true }],
    eligibility: { en: ["Orphaned / destitute child resident of UT"], hi: ["UT के अनाथ बच्चे"] },
    applyUrl: "https://ddd.gov.in",
  },
  {
    slug: "dl-mukhyamantri-tirth-yatra",
    name: { en: "Mukhyamantri Tirth Yatra Yojana", hi: "मुख्यमंत्री तीर्थ यात्रा योजना" },
    category: "Welfare",
    authority: "Delhi Revenue Department",
    state: "Delhi",
    processingTime: "30 days",
    fee: "Free",
    description: {
      en: "Free pilgrimage travel for senior citizens of Delhi to select religious destinations across India.",
      hi: "दिल्ली के वरिष्ठ नागरिकों को नि:शुल्क तीर्थ यात्रा।",
    },
    documents: [...baseDocs, { title: { en: "Age proof (60+ years)", hi: "आयु प्रमाण (60+)" }, required: true }],
    eligibility: { en: ["Resident of Delhi aged 60+ years", "Not a government employee"], hi: ["60+ वर्ष के दिल्ली निवासी"] },
    applyUrl: "https://edistrict.delhigovt.nic.in",
  },
  {
    slug: "jk-ladli-beti",
    name: { en: "Ladli Beti Scheme (J&K)", hi: "लाडली बेटी योजना" },
    category: "Welfare",
    authority: "J&K Social Welfare Department",
    state: "Jammu & Kashmir",
    processingTime: "60 days",
    fee: "Free",
    description: {
      en: "Monthly deposit by the J&K government for every girl child born after 1 April 2015 to eligible families.",
      hi: "जम्मू-कश्मीर सरकार द्वारा पात्र परिवारों की बेटी के लिए मासिक जमा।",
    },
    documents: [...baseDocs, { title: { en: "Birth certificate (after 01-04-2015)", hi: "जन्म प्रमाण" }, required: true }, { title: { en: "Income certificate (< ₹75,000)", hi: "आय प्रमाण" }, required: true }],
    eligibility: { en: ["Girl child born after 01-04-2015", "Family income up to ₹75,000 p.a."], hi: ["01-04-2015 के बाद जन्मी बालिका"] },
    applyUrl: "https://jksocialwelfare.nic.in",
  },
  {
    slug: "la-lahdc-scholarship",
    name: { en: "LAHDC Scholarship Scheme", hi: "एलएएचडीसी छात्रवृत्ति" },
    category: "Education",
    authority: "Ladakh Autonomous Hill Development Council",
    state: "Ladakh",
    processingTime: "Annual",
    fee: "Free",
    description: {
      en: "Scholarships for meritorious and economically weaker students of Ladakh pursuing higher education.",
      hi: "लद्दाख के मेधावी एवं आर्थिक रूप से कमज़ोर छात्रों के लिए छात्रवृत्ति।",
    },
    documents: [...baseDocs, { title: { en: "Previous year's marksheet", hi: "पिछले वर्ष की अंकतालिका" }, required: true }, { title: { en: "Income & resident certificate", hi: "आय एवं निवास प्रमाण" }, required: true }],
    eligibility: { en: ["Permanent resident of Ladakh", "Pursuing recognised higher education"], hi: ["लद्दाख का स्थायी निवासी"] },
    applyUrl: "https://leh.nic.in",
  },
  {
    slug: "ld-island-healthcare",
    name: { en: "Free Healthcare for Islanders", hi: "द्वीपवासियों के लिए नि:शुल्क स्वास्थ्य" },
    category: "Welfare",
    authority: "Lakshadweep Health Services",
    state: "Lakshadweep",
    processingTime: "Walk-in",
    fee: "Free",
    description: {
      en: "Free primary, secondary and referral healthcare for permanent residents of Lakshadweep, including airlifting for emergencies.",
      hi: "लक्षद्वीप के स्थायी निवासियों के लिए नि:शुल्क स्वास्थ्य सेवा।",
    },
    documents: [...baseDocs, { title: { en: "Permanent Resident Certificate", hi: "स्थायी निवास प्रमाण" }, required: true }],
    eligibility: { en: ["Permanent resident of Lakshadweep"], hi: ["लक्षद्वीप का स्थायी निवासी"] },
    applyUrl: "https://lakshadweep.gov.in",
  },
  {
    slug: "py-cmchis",
    name: { en: "CM's Comprehensive Health Insurance Scheme", hi: "मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना" },
    category: "Welfare",
    authority: "Puducherry Health Department",
    state: "Puducherry",
    processingTime: "15 days",
    fee: "Free",
    description: {
      en: "Cashless treatment cover up to ₹5 lakh per family per year for residents of Puducherry.",
      hi: "पुडुचेरी निवासियों को प्रति परिवार सालाना ₹5 लाख तक का कैशलेस इलाज।",
    },
    documents: [...baseDocs, { title: { en: "Ration / resident card", hi: "राशन / निवास कार्ड" }, required: true }],
    eligibility: { en: ["Resident family of Puducherry meeting income criteria"], hi: ["पुडुचेरी निवासी परिवार"] },
    applyUrl: "https://health.py.gov.in",
  },
];
