import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, BadgeCheck, Building2, Clock, Download, ExternalLink, IndianRupee, ListChecks, Printer } from "lucide-react";
import { useEffect } from "react";
import { services, type GovService } from "@/lib/services-data";
import { localized, useI18n } from "@/lib/i18n";
import { SiteHeader, SiteFooter, MobileTabBar } from "@/components/SiteHeader";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ShareButton } from "@/components/ShareButton";
import { useRecent } from "@/lib/user-prefs";

export const Route = createFileRoute("/services/$slug")({
  loader: ({ params }) => {
    const service = services.find((s) => s.slug === params.slug);
    if (!service) throw notFound();
    return { service };
  },
  head: ({ loaderData }) => {
    const s = loaderData?.service;
    return {
      meta: [
        { title: s ? `${s.name.en} — Documents Required | DocSetu` : "Service — DocSetu" },
        { name: "description", content: s ? `Documents, fees and processing time for ${s.name.en} application in India.` : "" },
      ],
    };
  },
  notFoundComponent: () => (
    <div className="min-h-screen grid place-items-center">
      <div className="text-center">
        <p className="text-muted-foreground">Service not found</p>
        <Link to="/services" className="text-primary underline mt-2 inline-block">Back to services</Link>
      </div>
    </div>
  ),
  component: ServiceDetail,
});

function ServiceDetail() {
  const { service } = Route.useLoaderData() as { service: GovService };
  const { t, lang } = useI18n();
  const elig = service.eligibility[lang === "hi" ? "hi" : "en"] ?? service.eligibility.en;
  const { push } = useRecent();

  useEffect(() => {
    push(service.slug);
  }, [service.slug, push]);

  const downloadChecklist = () => {
    const lines = [
      `${service.name.en} — Document Checklist`,
      `Authority: ${service.authority}`,
      `Processing: ${service.processingTime}`,
      `Fee: ${service.fee}`,
      "",
      "Documents:",
      ...service.documents.map(
        (d, i) =>
          `  ${i + 1}. [ ] ${d.title.en}${d.required ? " (Required)" : " (Optional)"}${d.note?.en ? ` — ${d.note.en}` : ""}`,
      ),
      "",
      "Eligibility:",
      ...service.eligibility.en.map((e) => `  • ${e}`),
      "",
      service.applyUrl ? `Apply: ${service.applyUrl}` : "",
      "Generated by DocSetu",
    ].filter(Boolean);
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${service.slug}-checklist.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col bg-background pb-24 md:pb-0">
      <SiteHeader />

      <section className="border-b border-border bg-hero">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-6 sm:py-12">
          <Link to="/services" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" /> {t("back")}
          </Link>
          <div className="mt-3 sm:mt-5 flex items-center gap-2 text-[11px] sm:text-xs uppercase tracking-[0.16em] font-semibold flex-wrap">
            <span className="w-1.5 h-1.5 rounded-full bg-saffron" />
            <span className="text-india-green">{service.category}</span>
            <span className="text-muted-foreground">· {service.authority}</span>
          </div>
          <h1 className="mt-2 sm:mt-3 font-display text-3xl sm:text-5xl md:text-6xl font-semibold leading-[1.08]">
            {localized(service.name, lang)}
          </h1>
          <p className="mt-3 sm:mt-4 text-base sm:text-lg text-muted-foreground max-w-3xl">{localized(service.description, lang)}</p>

          <div className="mt-6 sm:mt-8 grid grid-cols-1 sm:grid-cols-3 gap-2 sm:gap-3">
            <Meta icon={<Building2 className="w-4 h-4" />} label={t("authority")} value={service.authority} />
            <Meta icon={<Clock className="w-4 h-4" />} label={t("processingTime")} value={service.processingTime} />
            <Meta icon={<IndianRupee className="w-4 h-4" />} label={t("fee")} value={service.fee} />
          </div>

          <div className="mt-5 sm:mt-7 hidden sm:flex flex-wrap gap-3 print:hidden">
            {service.applyUrl && (
              <a
                href={service.applyUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-2 rounded-xl bg-saffron-gradient text-saffron-foreground font-semibold px-5 py-3 shadow-elevated hover:opacity-95 transition"
              >
                {t("applyOfficial")} <ExternalLink className="w-4 h-4" />
              </a>
            )}
            <button
              onClick={downloadChecklist}
              className="inline-flex items-center gap-2 rounded-xl border border-border bg-card font-semibold px-5 py-3 hover:border-primary/40 transition"
            >
              <Download className="w-4 h-4" /> Checklist
            </button>
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-2 rounded-xl border border-border bg-card font-semibold px-5 py-3 hover:border-primary/40 transition"
            >
              <Printer className="w-4 h-4" /> {t("print")}
            </button>
            <FavoriteButton slug={service.slug} />
            <ShareButton title={service.name.en} text={service.description.en} />

          </div>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 sm:px-6 py-8 sm:py-14 grid lg:grid-cols-[1.6fr_1fr] gap-8 lg:gap-10 w-full flex-1">
        <div>
          <h2 className="flex items-center gap-2 font-display text-xl sm:text-2xl font-semibold">
            <ListChecks className="w-5 h-5 text-india-green" />
            {t("documentsNeeded")}
          </h2>
          <ol className="mt-4 sm:mt-6 space-y-3">
            {service.documents.map((d, i) => (
              <li
                key={i}
                className="flex gap-3 sm:gap-4 rounded-xl border border-border bg-card p-3.5 sm:p-4 shadow-card"
              >
                <div className="shrink-0 w-9 h-9 rounded-lg bg-primary/5 border border-primary/15 flex items-center justify-center font-display font-semibold text-primary">
                  {i + 1}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start gap-2 flex-wrap">
                    <span className="font-medium">{localized(d.title, lang)}</span>
                    <span
                      className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded-full ${
                        d.required
                          ? "bg-india-green/10 text-india-green border border-india-green/20"
                          : "bg-muted text-muted-foreground border border-border"
                      }`}
                    >
                      {d.required ? t("required") : t("optional")}
                    </span>
                  </div>
                  {d.note && (
                    <p className="text-sm text-muted-foreground mt-1">{localized(d.note, lang)}</p>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </div>

        <aside>
          <h2 className="flex items-center gap-2 font-display text-xl sm:text-2xl font-semibold">
            <BadgeCheck className="w-5 h-5 text-saffron" />
            {t("eligibility")}
          </h2>
          <ul className="mt-4 sm:mt-6 space-y-3">
            {elig.map((e, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-saffron shrink-0" />
                <span className="text-foreground/85">{e}</span>
              </li>
            ))}
          </ul>

          <div className="mt-6 sm:mt-8 p-4 sm:p-5 rounded-2xl border border-border bg-secondary/60">
            <p className="text-xs text-muted-foreground leading-relaxed">
              {t("footerNote")}
            </p>
          </div>
        </aside>
      </section>

      {/* Mobile sticky action bar */}
      <div
        className="sm:hidden fixed bottom-14 inset-x-0 z-30 border-t border-border bg-background/95 backdrop-blur-xl px-3 py-2.5 flex gap-2 print:hidden"
        style={{ paddingBottom: "calc(0.625rem + env(safe-area-inset-bottom))" }}
      >
        {service.applyUrl && (
          <a
            href={service.applyUrl}
            target="_blank"
            rel="noreferrer"
            className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-saffron-gradient text-saffron-foreground font-semibold px-4 py-3 shadow-elevated text-sm"
          >
            {t("applyOfficial")} <ExternalLink className="w-4 h-4" />
          </a>
        )}
        <button
          onClick={downloadChecklist}
          aria-label="Download checklist"
          className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card font-semibold w-12 h-12"
        >
          <Download className="w-5 h-5" />
        </button>
        <button
          onClick={() => window.print()}
          aria-label={t("print")}
          className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card font-semibold w-12 h-12"
        >
          <Printer className="w-5 h-5" />
        </button>
        <FavoriteButton slug={service.slug} compact />
        <ShareButton title={service.name.en} text={service.description.en} compact />
      </div>


      <SiteFooter />
      <MobileTabBar />
    </div>
  );
}

function Meta({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card/70 backdrop-blur p-4 shadow-card">
      <div className="flex items-center gap-2 text-[11px] uppercase tracking-wider text-muted-foreground">
        {icon} {label}
      </div>
      <div className="mt-1 font-medium text-sm">{value}</div>
    </div>
  );
}
