import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, BadgeCheck, Building2, Clock, Download, IndianRupee, ListChecks, MapPin, Printer, Sparkles, FileText } from "lucide-react";
import { ApplyLink } from "@/components/ApplyLink";
import { useEffect } from "react";
import { services, type GovService } from "@/lib/services-data";
import { localized, useI18n } from "@/lib/i18n";
import { SiteHeader, SiteFooter, MobileTabBar } from "@/components/SiteHeader";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ShareButton } from "@/components/ShareButton";
import { useRecent } from "@/lib/user-prefs";

export const Route = createFileRoute("/services/$slug")({
  loader: ({ params }) => {
    const service = services.find((s) => s.slug === params.slug);
    if (!service) throw notFound();
    return { service };
  },
  head: ({ loaderData }) => {
    const s = loaderData?.service;
    return {
      meta: [
        { title: s ? `${s.name.en} — Documents Required | DocSetu` : "Service — DocSetu" },
        { name: "description", content: s ? `Documents, fees and processing time for ${s.name.en} application in India.` : "" },
      ],
    };
  },
  notFoundComponent: () => (
    <div className="min-h-screen grid place-items-center">
      <div className="text-center">
        <p className="text-muted-foreground">Service not found</p>
        <Link to="/services" className="text-primary underline mt-2 inline-block">Back to services</Link>
      </div>
    </div>
  ),
  component: ServiceDetail,
});

function ServiceDetail() {
  const { service } = Route.useLoaderData() as { service: GovService };
  const { t, lang } = useI18n();
  const elig = service.eligibility[lang === "hi" ? "hi" : "en"] ?? service.eligibility.en;
  const { push } = useRecent();

  useEffect(() => {
    push(service.slug);
  }, [service.slug, push]);

  const related = services
    .filter(
      (s) =>
        s.slug !== service.slug &&
        (s.category === service.category || (service.state && s.state === service.state)),
    )
    .slice(0, 3);

  const steps = [
    {
      title: "Gather your documents",
      desc: `Collect all ${service.documents.filter((d) => d.required).length} required documents listed below. Keep originals and self-attested photocopies ready.`,
    },
    {
      title: "Check your eligibility",
      desc: "Confirm you meet the eligibility criteria before applying to avoid rejection.",
    },
    {
      title: service.applyUrl ? "Apply online or visit office" : "Visit the issuing authority",
      desc: service.applyUrl
        ? `Submit your application on the official portal of ${service.authority}. Save the acknowledgement number.`
        : `Visit your nearest ${service.authority} office with documents during working hours.`,
    },
    {
      title: "Track and collect",
      desc: `Processing typically takes ${service.processingTime}. Use the acknowledgement number to track status online.`,
    },
  ];

  const downloadChecklist = () => {
    const lines = [
      `${service.name.en} — Document Checklist`,
      `Authority: ${service.authority}`,
      `Processing: ${service.processingTime}`,
      `Fee: ${service.fee}`,
      "",
      "Documents:",
      ...service.documents.map(
        (d, i) =>
          `  ${i + 1}. [ ] ${d.title.en}${d.required ? " (Required)" : " (Optional)"}${d.note?.en ? ` — ${d.note.en}` : ""}`,
      ),
      "",
      "Eligibility:",
      ...service.eligibility.en.map((e) => `  • ${e}`),
      "",
      service.applyUrl ? `Apply: ${service.applyUrl}` : "",
      "Generated by DocSetu",
    ].filter(Boolean);
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${service.slug}-checklist.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col bg-background pb-24 md:pb-0">
      <SiteHeader />

      <section className="border-b border-border bg-hero">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-6 sm:py-12">
          <Link to="/services" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" /> {t("back")}
          </Link>
          <div className="mt-3 sm:mt-5 flex items-center gap-2 text-[11px] sm:text-xs uppercase tracking-[0.16em] font-semibold flex-wrap">
            <span className="w-1.5 h-1.5 rounded-full bg-saffron" />
            <span className="text-india-green">{service.category}</span>
            <span className="text-muted-foreground">· {service.authority}</span>
          </div>
          <h1 className="mt-2 sm:mt-3 font-display text-3xl sm:text-5xl md:text-6xl font-semibold leading-[1.08]">
            {localized(service.name, lang)}
          </h1>
          <p className="mt-3 sm:mt-4 text-base sm:text-lg text-muted-foreground max-w-3xl">{localized(service.description, lang)}</p>

          <div className="mt-6 sm:mt-8 grid grid-cols-1 sm:grid-cols-3 gap-2 sm:gap-3">
            <Meta icon={<Building2 className="w-4 h-4" />} label={t("authority")} value={service.authority} />
            <Meta icon={<Clock className="w-4 h-4" />} label={t("processingTime")} value={service.processingTime} />
            <Meta icon={<IndianRupee className="w-4 h-4" />} label={t("fee")} value={service.fee} />
          </div>

          <div className="mt-5 sm:mt-7 hidden sm:flex flex-wrap gap-3 print:hidden">
            {service.applyUrl && (
              <ApplyLink
                href={service.applyUrl}
                serviceName={localized(service.name, "en")}
                authority={service.authority}
                iconClassName="w-4 h-4"
                className="inline-flex items-center gap-2 rounded-xl bg-saffron-gradient text-saffron-foreground font-semibold px-5 py-3 shadow-elevated hover:opacity-95 transition focus:outline-none focus-visible:ring-2 focus-visible:ring-ring/60"
              >
                {t("applyOfficial")}
              </ApplyLink>
            )}
            <button
              onClick={downloadChecklist}
              className="inline-flex items-center gap-2 rounded-xl border border-border bg-card font-semibold px-5 py-3 hover:border-primary/40 transition"
            >
              <Download className="w-4 h-4" /> Checklist
            </button>
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-2 rounded-xl border border-border bg-card font-semibold px-5 py-3 hover:border-primary/40 transition"
            >
              <Printer className="w-4 h-4" /> {t("print")}
            </button>
            <FavoriteButton slug={service.slug} />
            <ShareButton title={service.name.en} text={service.description.en} />

          </div>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 sm:px-6 py-8 sm:py-14 grid lg:grid-cols-[1.6fr_1fr] gap-8 lg:gap-10 w-full flex-1">
        <div>
          <h2 className="flex items-center gap-2 font-display text-xl sm:text-2xl font-semibold">
            <ListChecks className="w-5 h-5 text-india-green" />
            {t("documentsNeeded")}
          </h2>
          <ol className="mt-4 sm:mt-6 space-y-3">
            {service.documents.map((d, i) => (
              <li
                key={i}
                className="flex gap-3 sm:gap-4 rounded-xl border border-border bg-card p-3.5 sm:p-4 shadow-card"
              >
                <div className="shrink-0 w-9 h-9 rounded-lg bg-primary/5 border border-primary/15 flex items-center justify-center font-display font-semibold text-primary">
                  {i + 1}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start gap-2 flex-wrap">
                    <span className="font-medium">{localized(d.title, lang)}</span>
                    <span
                      className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded-full ${
                        d.required
                          ? "bg-india-green/10 text-india-green border border-india-green/20"
                          : "bg-muted text-muted-foreground border border-border"
                      }`}
                    >
                      {d.required ? t("required") : t("optional")}
                    </span>
                  </div>
                  {d.note && (
                    <p className="text-sm text-muted-foreground mt-1">{localized(d.note, lang)}</p>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </div>

        <aside>
          <h2 className="flex items-center gap-2 font-display text-xl sm:text-2xl font-semibold">
            <BadgeCheck className="w-5 h-5 text-saffron" />
            {t("eligibility")}
          </h2>
          <ul className="mt-4 sm:mt-6 space-y-3">
            {elig.map((e, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-saffron shrink-0" />
                <span className="text-foreground/85">{e}</span>
              </li>
            ))}
          </ul>

          <div className="mt-6 sm:mt-8 p-4 sm:p-5 rounded-2xl border border-border bg-secondary/60">
            <p className="text-xs text-muted-foreground leading-relaxed">
              {t("footerNote")}
            </p>
          </div>
        </aside>
      </section>

      {/* How to apply */}
      <section className="border-t border-border bg-secondary/40 print:hidden">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-10 sm:py-14">
          <h2 className="font-display text-xl sm:text-2xl font-semibold flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-saffron" /> How to apply
          </h2>
          <ol className="mt-6 grid gap-3 sm:gap-4 sm:grid-cols-2">
            {steps.map((s, i) => (
              <li key={i} className="rounded-2xl border border-border bg-card p-4 sm:p-5 shadow-card">
                <div className="flex items-center gap-3">
                  <div className="shrink-0 w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center font-display font-semibold text-primary text-sm">
                    {i + 1}
                  </div>
                  <div className="font-semibold">{s.title}</div>
                </div>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{s.desc}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Related */}
      {related.length > 0 && (
        <section className="border-t border-border print:hidden">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 py-10 sm:py-14">
            <div className="flex items-end justify-between gap-4 mb-5">
              <h2 className="font-display text-xl sm:text-2xl font-semibold">Related services</h2>
              <Link to="/services" className="text-sm text-primary hover:underline inline-flex items-center gap-1.5">
                See all <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
            <div className="grid gap-3 sm:grid-cols-3">
              {related.map((r) => (
                <Link
                  key={r.slug}
                  to="/services/$slug"
                  params={{ slug: r.slug }}
                  aria-label={`View details for ${localized(r.name, lang)}`}
                  className="group rounded-2xl border border-border bg-card p-4 shadow-card hover:shadow-elevated hover:-translate-y-0.5 transition-all cursor-pointer"
                >
                  <div className="text-[10px] uppercase tracking-[0.14em] font-semibold text-india-green">
                    {r.category}
                  </div>
                  <div className="mt-1.5 font-display text-base font-semibold leading-tight">
                    {localized(r.name, lang)}
                  </div>
                  <div className="mt-1 text-xs text-muted-foreground truncate">{r.authority}</div>
                  <div className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary">
                    View <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-0.5" />
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}


      {/* Mobile sticky action bar */}
      <div
        className="sm:hidden fixed bottom-14 inset-x-0 z-30 border-t border-border bg-background/95 backdrop-blur-xl px-3 py-2.5 flex gap-2 print:hidden"
        style={{ paddingBottom: "calc(0.625rem + env(safe-area-inset-bottom))" }}
      >
        {service.applyUrl && (
          <ApplyLink
            href={service.applyUrl}
            serviceName={localized(service.name, "en")}
            authority={service.authority}
            iconClassName="w-4 h-4"
            className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-saffron-gradient text-saffron-foreground font-semibold px-4 py-3 shadow-elevated text-sm focus:outline-none focus-visible:ring-2 focus-visible:ring-ring/60"
          >
            {t("applyOfficial")}
          </ApplyLink>
        )}
        <button
          onClick={downloadChecklist}
          aria-label="Download checklist"
          className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card font-semibold w-12 h-12"
        >
          <Download className="w-5 h-5" />
        </button>
        <button
          onClick={() => window.print()}
          aria-label={t("print")}
          className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card font-semibold w-12 h-12"
        >
          <Printer className="w-5 h-5" />
        </button>
        <FavoriteButton slug={service.slug} compact />
        <ShareButton title={service.name.en} text={service.description.en} compact />
      </div>



      {/* Summary foot bar */}
      <section aria-labelledby="service-summary-heading" className="border-t border-border bg-card/40 print:border-t-2">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-8 sm:py-10">
          <h2 id="service-summary-heading" className="font-display text-lg sm:text-xl font-semibold">
            Quick summary
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            At-a-glance details for {localized(service.name, lang)} before you begin.
          </p>
          <div className="mt-5 grid gap-3 sm:gap-4 sm:grid-cols-3">
            <div className="rounded-2xl border border-border bg-card p-4 sm:p-5">
              <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.14em] font-semibold text-india-green">
                <MapPin className="w-3.5 h-3.5" /> Availability
              </div>
              <div className="mt-2 font-medium text-sm">{service.authority}</div>
              <ul className="mt-2 space-y-1 text-xs text-muted-foreground">
                <li>Coverage: {service.state ? `${service.state} (state)` : "All India"}</li>
                <li>Processing: {service.processingTime}</li>
                <li>Fee: {service.fee}</li>
                <li>Apply: {service.applyUrl ? "Online + in-person" : "In-person only"}</li>
              </ul>
            </div>

            <div className="rounded-2xl border border-border bg-card p-4 sm:p-5">
              <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.14em] font-semibold text-saffron">
                <BadgeCheck className="w-3.5 h-3.5" /> Eligibility notes
              </div>
              <ul className="mt-2 space-y-1.5 text-xs text-foreground/85">
                {elig.slice(0, 3).map((e, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="mt-1 w-1 h-1 rounded-full bg-saffron shrink-0" />
                    <span className="line-clamp-2">{e}</span>
                  </li>
                ))}
                {elig.length > 3 && (
                  <li className="text-muted-foreground">+ {elig.length - 3} more criteria above</li>
                )}
              </ul>
            </div>

            <div className="rounded-2xl border border-border bg-card p-4 sm:p-5">
              <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.14em] font-semibold text-primary">
                <FileText className="w-3.5 h-3.5" /> Data & documents needed
              </div>
              <div className="mt-2 text-xs text-muted-foreground">
                <span className="font-semibold text-foreground">
                  {service.documents.filter((d) => d.required).length} required
                </span>
                {service.documents.some((d) => !d.required) && (
                  <> · {service.documents.filter((d) => !d.required).length} optional</>
                )}
              </div>
              <ul className="mt-2 space-y-1 text-xs text-foreground/85">
                {service.documents
                  .filter((d) => d.required)
                  .slice(0, 4)
                  .map((d, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="mt-1 w-1 h-1 rounded-full bg-india-green shrink-0" />
                      <span className="line-clamp-1">{localized(d.title, lang)}</span>
                    </li>
                  ))}
                {service.documents.filter((d) => d.required).length > 4 && (
                  <li className="text-muted-foreground">
                    + {service.documents.filter((d) => d.required).length - 4} more in checklist
                  </li>
                )}
              </ul>
            </div>
          </div>

          <p className="mt-5 text-[11px] text-muted-foreground leading-relaxed">
            {t("footerNote")}
          </p>
        </div>
      </section>

      <SiteFooter />
      <MobileTabBar />
    </div>
  );
}

function Meta({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card/70 backdrop-blur p-4 shadow-card">
      <div className="flex items-center gap-2 text-[11px] uppercase tracking-wider text-muted-foreground">
        {icon} {label}
      </div>
      <div className="mt-1 font-medium text-sm">{value}</div>
    </div>
  );
}
