import { Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Bookmark, Building2, Clock, Download, IndianRupee, ListChecks, Printer } from "lucide-react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { ApplyLink } from "@/components/ApplyLink";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ShareButton } from "@/components/ShareButton";
import type { GovService } from "@/lib/services-data";
import { localized, useI18n } from "@/lib/i18n";

export function ServiceDetailsDrawer({
  service,
  open,
  onOpenChange,
}: {
  service: GovService;
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const { t, lang } = useI18n();
  const name = localized(service.name, lang);
  const elig = service.eligibility[lang === "hi" ? "hi" : "en"] ?? service.eligibility.en;

  const downloadChecklist = () => {
    const lines = [
      `${service.name.en} — Document Checklist`,
      `Authority: ${service.authority}`,
      `Processing: ${service.processingTime}`,
      `Fee: ${service.fee}`,
      "",
      "Documents:",
      ...service.documents.map(
        (d, i) =>
          `  ${i + 1}. [ ] ${d.title.en}${d.required ? " (Required)" : " (Optional)"}${d.note?.en ? ` — ${d.note.en}` : ""}`,
      ),
      "",
      "Eligibility:",
      ...service.eligibility.en.map((e) => `  • ${e}`),
      "",
      service.applyUrl ? `Apply: ${service.applyUrl}` : "",
      "Generated by DocSetu",
    ].filter(Boolean);
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${service.slug}-checklist.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="w-full sm:max-w-xl p-0 flex flex-col gap-0 overflow-hidden"
      >
        <SheetHeader className="px-5 sm:px-6 pt-6 pb-4 border-b border-border space-y-2 text-left">
          <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.16em] font-semibold flex-wrap pr-8">
            <span className="w-1.5 h-1.5 rounded-full bg-saffron" />
            <span className="text-india-green">{service.category}</span>
            <span className="text-muted-foreground">· {service.authority}</span>
            {service.state && (
              <span className="text-muted-foreground">· {service.state}</span>
            )}
          </div>
          <SheetTitle className="font-display text-2xl sm:text-3xl font-semibold leading-tight">
            {name}
          </SheetTitle>
          <SheetDescription className="text-sm text-muted-foreground">
            {localized(service.description, lang)}
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto px-5 sm:px-6 py-5 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            <Meta icon={<Building2 className="w-4 h-4" />} label={t("authority")} value={service.authority} />
            <Meta icon={<Clock className="w-4 h-4" />} label={t("processingTime")} value={service.processingTime} />
            <Meta icon={<IndianRupee className="w-4 h-4" />} label={t("fee")} value={service.fee} />
          </div>

          <section>
            <h3 className="flex items-center gap-2 font-display text-lg font-semibold">
              <ListChecks className="w-4 h-4 text-india-green" />
              {t("documentsNeeded")}
            </h3>
            <ol className="mt-3 space-y-2.5">
              {service.documents.map((d, i) => (
                <li key={i} className="flex gap-3 rounded-xl border border-border bg-card p-3">
                  <div className="shrink-0 w-8 h-8 rounded-lg bg-primary/5 border border-primary/15 flex items-center justify-center font-display font-semibold text-primary text-sm">
                    {i + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start gap-2 flex-wrap">
                      <span className="font-medium text-sm">{localized(d.title, lang)}</span>
                      <span
                        className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded-full ${
                          d.required
                            ? "bg-india-green/10 text-india-green border border-india-green/20"
                            : "bg-muted text-muted-foreground border border-border"
                        }`}
                      >
                        {d.required ? t("required") : t("optional")}
                      </span>
                    </div>
                    {d.note && (
                      <p className="text-xs text-muted-foreground mt-1">{localized(d.note, lang)}</p>
                    )}
                  </div>
                </li>
              ))}
            </ol>
          </section>

          <section>
            <h3 className="flex items-center gap-2 font-display text-lg font-semibold">
              <BadgeCheck className="w-4 h-4 text-saffron" />
              {t("eligibility")}
            </h3>
            <ul className="mt-3 space-y-2">
              {elig.map((e, i) => (
                <li key={i} className="flex gap-2.5 text-sm">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-saffron shrink-0" />
                  <span className="text-foreground/85">{e}</span>
                </li>
              ))}
            </ul>
          </section>

          <div className="p-4 rounded-xl border border-border bg-secondary/60">
            <p className="text-xs text-muted-foreground leading-relaxed">{t("footerNote")}</p>
          </div>

          <Link
            to="/services/$slug"
            params={{ slug: service.slug }}
            onClick={() => onOpenChange(false)}
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:underline"
          >
            Open full page <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        <div
          className="border-t border-border bg-background/95 backdrop-blur px-4 sm:px-6 py-3 flex flex-wrap gap-2"
          style={{ paddingBottom: "calc(0.75rem + env(safe-area-inset-bottom))" }}
        >
          {service.applyUrl && (
            <ApplyLink
              href={service.applyUrl}
              serviceName={name}
              authority={service.authority}
              iconClassName="w-4 h-4"
              className="flex-1 min-w-[8rem] inline-flex items-center justify-center gap-2 rounded-xl bg-saffron-gradient text-saffron-foreground font-semibold px-4 py-2.5 shadow-elevated text-sm focus:outline-none focus-visible:ring-2 focus-visible:ring-ring/60"
            >
              {t("applyOfficial")}
            </ApplyLink>
          )}
          <button
            onClick={downloadChecklist}
            aria-label="Download checklist"
            className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card w-11 h-11"
          >
            <Download className="w-4 h-4" />
          </button>
          <button
            onClick={() => window.print()}
            aria-label={t("print")}
            className="shrink-0 inline-flex items-center justify-center rounded-xl border border-border bg-card w-11 h-11"
          >
            <Printer className="w-4 h-4" />
          </button>
          <FavoriteButton slug={service.slug} compact />
          <ShareButton title={service.name.en} text={service.description.en} compact />
        </div>
      </SheetContent>
    </Sheet>
  );
}

function Meta({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card/70 backdrop-blur p-3">
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-muted-foreground">
        {icon} {label}
      </div>
      <div className="mt-0.5 font-medium text-sm">{value}</div>
    </div>
  );
}
