// Generates src/lib/services-catalog.ts with a broad catalog of
// central + state government services (per state templates).
import { writeFileSync } from "node:fs";

const STATES = [
  ["Andhra Pradesh", "ap", "https://ap.gov.in"],
  ["Arunachal Pradesh", "ar", "https://arunachalpradesh.gov.in"],
  ["Assam", "as", "https://assam.gov.in"],
  ["Bihar", "br", "https://state.bihar.gov.in"],
  ["Chhattisgarh", "cg", "https://cgstate.gov.in"],
  ["Goa", "ga", "https://goa.gov.in"],
  ["Gujarat", "gj", "https://gujaratindia.gov.in"],
  ["Haryana", "hr", "https://haryana.gov.in"],
  ["Himachal Pradesh", "hp", "https://himachal.gov.in"],
  ["Jharkhand", "jh", "https://jharkhand.gov.in"],
  ["Karnataka", "ka", "https://karnataka.gov.in"],
  ["Kerala", "kl", "https://kerala.gov.in"],
  ["Madhya Pradesh", "mp", "https://mp.gov.in"],
  ["Maharashtra", "mh", "https://maharashtra.gov.in"],
  ["Manipur", "mn", "https://manipur.gov.in"],
  ["Meghalaya", "ml", "https://meghalaya.gov.in"],
  ["Mizoram", "mz", "https://mizoram.gov.in"],
  ["Nagaland", "nl", "https://nagaland.gov.in"],
  ["Odisha", "od", "https://odisha.gov.in"],
  ["Punjab", "pb", "https://punjab.gov.in"],
  ["Rajasthan", "rj", "https://rajasthan.gov.in"],
  ["Sikkim", "sk", "https://sikkim.gov.in"],
  ["Tamil Nadu", "tn", "https://tn.gov.in"],
  ["Telangana", "tg", "https://telangana.gov.in"],
  ["Tripura", "tr", "https://tripura.gov.in"],
  ["Uttar Pradesh", "up", "https://up.gov.in"],
  ["Uttarakhand", "uk", "https://uk.gov.in"],
  ["West Bengal", "wb", "https://wb.gov.in"],
  ["Andaman & Nicobar Islands", "an", "https://andaman.gov.in"],
  ["Chandigarh", "ch", "https://chandigarh.gov.in"],
  ["Dadra & Nagar Haveli and Daman & Diu", "dd", "https://ddd.gov.in"],
  ["Delhi", "dl", "https://delhi.gov.in"],
  ["Jammu & Kashmir", "jk", "https://jk.gov.in"],
  ["Ladakh", "la", "https://ladakh.gov.in"],
  ["Lakshadweep", "ld", "https://lakshadweep.gov.in"],
  ["Puducherry", "py", "https://py.gov.in"],
];

// Per-state service templates. {state} substituted at emit time.
const STATE_TEMPLATES = [
  { key: "domicile", cat: "Identity", en: "Domicile / Residence Certificate", hi: "निवास प्रमाण पत्र", auth: "Revenue Department", time: "15–30 days", fee: "₹10–₹50",
    desc: "Proof of permanent residence of {state}, required for state-quota admissions, jobs and welfare schemes.",
    docs: ["Aadhaar Card", "Proof of address (electricity / water bill)", "Ration card or voter ID", "Self-declaration / affidavit", "Passport-size photograph"],
    elig: ["Person residing continuously in {state} for the minimum period prescribed by the state"] },
  { key: "caste", cat: "Identity", en: "Caste Certificate (SC/ST/OBC)", hi: "जाति प्रमाण पत्र", auth: "Revenue Department", time: "21–30 days", fee: "₹10–₹50",
    desc: "Certifies caste category for reservation in education, employment and government schemes.",
    docs: ["Aadhaar Card", "Father's / blood relative's caste certificate", "Domicile proof", "Ration card", "Self-declaration"],
    elig: ["Resident of {state} belonging to a notified SC/ST/OBC community"] },
  { key: "income", cat: "Welfare", en: "Income Certificate", hi: "आय प्रमाण पत्र", auth: "Revenue Department", time: "15 days", fee: "₹10–₹40",
    desc: "Certifies annual family income for fee waivers, scholarships and welfare scheme eligibility.",
    docs: ["Aadhaar Card", "Salary slip / Form 16 / ITR", "Ration card", "Self-declaration of income", "Domicile proof"],
    elig: ["Any resident of {state} requiring proof of family income"] },
  { key: "ews", cat: "Welfare", en: "EWS Certificate", hi: "ईडब्ल्यूएस प्रमाण पत्र", auth: "Revenue Department", time: "15–30 days", fee: "₹10–₹50",
    desc: "Economically Weaker Section certificate for 10% reservation in education and central/state jobs.",
    docs: ["Aadhaar Card", "Income proof (family income under ₹8 lakh)", "Land holding proof", "Self-declaration"],
    elig: ["Family income below ₹8 lakh per annum", "Agricultural land below 5 acres and limited urban property"] },
  { key: "birth", cat: "Civic", en: "Birth Certificate", hi: "जन्म प्रमाण पत्र", auth: "Municipal Corporation / Registrar of Births", time: "7–21 days", fee: "Free–₹50",
    desc: "Official record of birth issued under the Registration of Births and Deaths Act for residents of {state}.",
    docs: ["Hospital discharge summary / birth proof", "Parents' Aadhaar / ID proof", "Parents' marriage certificate", "Address proof"],
    elig: ["Any child born within {state}, registered by parents or hospital"] },
  { key: "death", cat: "Civic", en: "Death Certificate", hi: "मृत्यु प्रमाण पत्र", auth: "Municipal Corporation / Registrar", time: "7–21 days", fee: "Free–₹50",
    desc: "Official certification of death required for inheritance, insurance, pension and property transfers.",
    docs: ["Medical certificate of cause of death", "Deceased's Aadhaar / ID", "Applicant's ID proof", "Address proof"],
    elig: ["Death occurred within {state}; applied by family member or hospital"] },
  { key: "marriage", cat: "Civic", en: "Marriage Registration", hi: "विवाह पंजीकरण", auth: "Registrar of Marriages / Municipal Corporation", time: "15–30 days", fee: "₹100–₹500",
    desc: "Statutory registration of marriage under the Hindu Marriage Act / Special Marriage Act for residents of {state}.",
    docs: ["Both parties' Aadhaar / ID proof", "Address proof", "Date of birth proof", "Marriage invitation / photographs", "Witnesses' ID proof"],
    elig: ["Both spouses are residents of {state}", "Bride 18+, groom 21+"] },
  { key: "ration", cat: "Welfare", en: "Ration Card (NFSA)", hi: "राशन कार्ड", auth: "Food, Civil Supplies & Consumer Affairs Dept.", time: "30 days", fee: "Free–₹50",
    desc: "Entitlement card for subsidised food grains under the National Food Security Act, issued by {state}.",
    docs: ["Aadhaar of all family members", "Address proof", "Income proof", "Family photograph", "Surrender certificate of previous card (if any)"],
    elig: ["Family ordinarily residing in {state}", "Annual income within NFSA limits for the state"] },
  { key: "oldage", cat: "Welfare", en: "Old Age Pension", hi: "वृद्धावस्था पेंशन", auth: "Social Welfare Department", time: "30–60 days", fee: "Free",
    desc: "Monthly pension for senior citizens belonging to BPL households in {state}.",
    docs: ["Aadhaar Card", "Age proof", "BPL ration card", "Bank passbook (Aadhaar-linked)", "Passport-size photograph"],
    elig: ["Resident of {state} aged 60 years or above", "Belongs to BPL category"] },
  { key: "widow", cat: "Welfare", en: "Widow Pension", hi: "विधवा पेंशन", auth: "Social Welfare Department", time: "30–60 days", fee: "Free",
    desc: "Monthly financial assistance to widows from economically weaker families in {state}.",
    docs: ["Aadhaar Card", "Husband's death certificate", "BPL / income proof", "Bank passbook", "Photograph"],
    elig: ["Widow resident of {state}", "Family income within prescribed limit"] },
  { key: "disability", cat: "Welfare", en: "Disability Pension", hi: "दिव्यांग पेंशन", auth: "Social Welfare Department", time: "30–60 days", fee: "Free",
    desc: "Monthly pension for persons with 40%+ disability under the state social security framework.",
    docs: ["Aadhaar Card", "UDID / disability certificate", "Income proof", "Bank passbook", "Photograph"],
    elig: ["Resident of {state} with 40% or higher certified disability"] },
  { key: "udid", cat: "Identity", en: "Disability Certificate (UDID)", hi: "दिव्यांगता प्रमाण पत्र", auth: "District Medical Board (with MoSJE)", time: "30–60 days", fee: "Free",
    desc: "Unique Disability ID and certificate issued after medical assessment, accepted across India.",
    docs: ["Aadhaar Card", "Recent photograph", "Medical reports of disability", "Address proof"],
    elig: ["Person with disability as defined under the RPwD Act, 2016"] },
  { key: "land", cat: "Property", en: "Land Records / Bhulekh (RoR)", hi: "भू-अभिलेख", auth: "Revenue / Land Records Department", time: "Instant–7 days", fee: "₹10–₹50 per copy",
    desc: "Record of Rights (Khatauni / 7-12 / Patta) issued by the {state} land records portal.",
    docs: ["Khasra / survey number", "Owner's name and Aadhaar", "Village & tehsil details"],
    elig: ["Any landowner / lessee of agricultural or urban land in {state}"] },
  { key: "mutation", cat: "Property", en: "Property Mutation", hi: "नामांतरण", auth: "Revenue Department / Municipal Corporation", time: "30–45 days", fee: "₹100–₹500",
    desc: "Transfer of title in revenue / municipal records after sale, inheritance or gift of property in {state}.",
    docs: ["Sale deed / will / gift deed", "Previous RoR / property tax receipt", "Aadhaar of applicant", "No-objection from co-owners (if any)"],
    elig: ["Owner of property situated in {state} after a valid transfer event"] },
  { key: "ec", cat: "Property", en: "Encumbrance Certificate", hi: "ऋणभार प्रमाण पत्र", auth: "Sub-Registrar Office", time: "7–15 days", fee: "₹100–₹500",
    desc: "Certificate listing all registered transactions on a property over a given period in {state}.",
    docs: ["Property address & survey number", "Sale deed copy", "Aadhaar of applicant"],
    elig: ["Any property owner / prospective buyer in {state}"] },
  { key: "trade", cat: "Civic", en: "Trade Licence", hi: "व्यापार लाइसेंस", auth: "Municipal Corporation / Local Body", time: "15–30 days", fee: "Varies by trade",
    desc: "Mandatory licence to operate a trade, shop or business within municipal limits of {state}.",
    docs: ["Aadhaar / PAN of proprietor", "Address proof of premises", "Rent agreement / ownership proof", "NOC from owner", "Site plan"],
    elig: ["Any person / firm operating a trade within municipal limits of {state}"] },
  { key: "building", cat: "Property", en: "Building Plan Approval", hi: "भवन निर्माण अनुमति", auth: "Town & Country Planning / Municipal Corporation", time: "30–60 days", fee: "Per sq.m of built-up area",
    desc: "Sanction of building plans for new construction or major alterations in {state}.",
    docs: ["Title deed / land ownership proof", "Architectural drawings", "Structural design certificate", "Soil test report", "ID proof of owner"],
    elig: ["Land/plot owner in {state} undertaking new construction or extension"] },
  { key: "water", cat: "Civic", en: "New Water Connection", hi: "नया जल कनेक्शन", auth: "Public Health Engineering / Jal Board", time: "15–30 days", fee: "Varies",
    desc: "Application for a domestic / commercial water supply connection in {state}.",
    docs: ["Aadhaar Card", "Property tax receipt", "Ownership / rent proof", "Site plan"],
    elig: ["Property owner / occupier within the service area"] },
  { key: "electricity", cat: "Civic", en: "New Electricity Connection", hi: "नया विद्युत कनेक्शन", auth: "State Electricity Distribution Company", time: "7–30 days", fee: "Per kW load",
    desc: "Domestic / commercial / industrial power connection from the {state} discom.",
    docs: ["Aadhaar Card", "Property ownership / rent proof", "Latest electricity bill of neighbour (for reference)", "Wiring contractor test report"],
    elig: ["Owner / occupier of premises within the discom's licensed area"] },
  { key: "prematric", cat: "Education", en: "Pre-Matric Scholarship", hi: "प्री-मैट्रिक छात्रवृत्ति", auth: "Social Welfare / Minority Welfare Department", time: "60–90 days", fee: "Free",
    desc: "Financial assistance to SC/ST/OBC/Minority students in classes 1–10 studying in {state}.",
    docs: ["Aadhaar Card", "Caste / minority certificate", "Income certificate", "Bonafide certificate from school", "Bank passbook"],
    elig: ["Student studying in classes 1–10 in a recognised school in {state}", "Family income within prescribed ceiling"] },
  { key: "postmatric", cat: "Education", en: "Post-Matric Scholarship", hi: "पोस्ट-मैट्रिक छात्रवृत्ति", auth: "Social Welfare / Minority Welfare Department", time: "60–120 days", fee: "Free",
    desc: "Tuition fee and maintenance allowance for SC/ST/OBC/Minority students pursuing post-matric studies in {state}.",
    docs: ["Aadhaar Card", "Caste / minority certificate", "Income certificate", "Previous year mark sheet", "Bonafide certificate from institution", "Bank passbook"],
    elig: ["Student pursuing recognised course beyond class 10 in {state}", "Family income within prescribed ceiling"] },
  { key: "legalheir", cat: "Civic", en: "Legal Heir / Succession Certificate", hi: "वारिस प्रमाण पत्र", auth: "Tahsildar / Revenue Department", time: "30–45 days", fee: "₹10–₹200",
    desc: "Certifies the legal heirs of a deceased person in {state}, required for pension transfer, insurance claims and property inheritance.",
    docs: ["Death certificate of the deceased", "Aadhaar Card of applicant", "Family member details with ID proof", "Self-declaration / affidavit on stamp paper", "Address proof of the deceased", "Ration card showing family members"],
    elig: ["Spouse, child, parent or sibling of a person who died while resident in {state}"] },
  { key: "solvency", cat: "Finance", en: "Solvency Certificate", hi: "विलायकता प्रमाण पत्र", auth: "Tahsildar / Revenue Department", time: "15–30 days", fee: "₹50–₹500",
    desc: "Certifies the financial soundness and asset value of an applicant in {state}, commonly required for tenders, bank guarantees and visas.",
    docs: ["Aadhaar Card and PAN", "Property documents / land records", "Bank statement of last 6 months", "Income tax returns of last 3 years", "Valuation report of assets", "Application on prescribed form"],
    elig: ["Resident of {state} holding assets within the district"] },
  { key: "seniorcitizen", cat: "Welfare", en: "Senior Citizen Identity Card", hi: "वरिष्ठ नागरिक पहचान पत्र", auth: "Social Welfare Department", time: "15–30 days", fee: "Free–₹50",
    desc: "Identity card giving senior citizens of {state} concessions in travel, healthcare and government services.",
    docs: ["Aadhaar Card", "Age proof (birth certificate / school certificate)", "Address proof", "Two passport-size photographs", "Blood group / medical details (optional)"],
    elig: ["Resident of {state} aged 60 years or above"] },
  { key: "labourcard", cat: "Welfare", en: "Labour Card (BOCW Registration)", hi: "श्रमिक कार्ड", auth: "Building & Other Construction Workers Welfare Board", time: "15–30 days", fee: "₹20–₹50 + monthly contribution",
    desc: "Registration of construction workers with the {state} welfare board for accident cover, maternity aid, education and housing benefits.",
    docs: ["Aadhaar Card", "Employment certificate from contractor / 90-day work proof", "Bank passbook (Aadhaar-linked)", "Age proof", "Passport-size photographs", "Ration card"],
    elig: ["Aged 18–60 years", "Worked at least 90 days as a construction worker in {state} in the last year"] },
  { key: "shopact", cat: "Civic", en: "Shop & Establishment Registration", hi: "दुकान एवं स्थापना पंजीकरण", auth: "Labour Department / Municipal Corporation", time: "7–30 days", fee: "₹100–₹2,000 by employee count",
    desc: "Mandatory registration for any shop, office or commercial establishment operating in {state} under the Shops and Establishments Act.",
    docs: ["Aadhaar / PAN of proprietor or partners", "Address proof of the establishment", "Rent agreement or ownership document", "Photograph of the shop front with signboard", "List of employees with details", "Partnership deed / incorporation certificate (if applicable)"],
    elig: ["Any shop, commercial establishment or office operating within {state}"] },
  { key: "firenoc", cat: "Civic", en: "Fire Safety NOC", hi: "अग्नि सुरक्षा एनओसी", auth: "State Fire & Emergency Services", time: "30–45 days", fee: "Based on built-up area",
    desc: "No-objection certificate from the {state} fire service confirming a building meets fire safety norms; required for occupancy and trade licences.",
    docs: ["Building plan approved by the local body", "Ownership / lease documents", "Fire fighting system layout and installation certificate", "Structural stability certificate", "Application on prescribed form"],
    elig: ["Owner or occupier of a high-rise, commercial, industrial or public building in {state}"] },
  { key: "propertytax", cat: "Property", en: "Property Tax Assessment & Payment", hi: "संपत्ति कर", auth: "Municipal Corporation / Urban Local Body", time: "Instant–15 days", fee: "Per annual rateable value",
    desc: "Assessment, self-assessment and online payment of municipal property tax for properties in {state}.",
    docs: ["Property ID / assessment number", "Sale deed or allotment letter", "Previous property tax receipt", "Aadhaar of the owner", "Building completion / occupancy certificate"],
    elig: ["Owner of any residential or commercial property within a municipal area of {state}"] },
  { key: "farmer", cat: "Welfare", en: "Farmer Registration & Crop Subsidy", hi: "किसान पंजीकरण", auth: "Department of Agriculture", time: "15–30 days", fee: "Free",
    desc: "Registration of farmers in {state} for seed, fertiliser and equipment subsidies, crop insurance and minimum support price procurement.",
    docs: ["Aadhaar Card", "Land records (Khasra / Khatauni / 7-12 / Patta)", "Bank passbook (Aadhaar-linked)", "Passport-size photograph", "Mobile number linked with Aadhaar"],
    elig: ["Cultivator owning or leasing agricultural land in {state}"] },
];

// Real state service portals used for the Apply link of each template.
const PORTALS = {
  ap: { edistrict: "https://vswsonline.ap.gov.in", land: "https://meebhoomi.ap.gov.in", ration: "https://epos.ap.gov.in", igrs: "https://registration.ap.gov.in", power: "https://www.apeasternpower.com", scholarship: "https://jnanabhumi.ap.gov.in", ulb: "https://cdma.ap.gov.in", labour: "https://labour.ap.gov.in", agri: "https://apagrisnet.gov.in" },
  ar: { edistrict: "https://eservice.arunachal.gov.in", ration: "https://arunfcs.gov.in", power: "https://power.arunachal.gov.in" },
  as: { edistrict: "https://sewasetu.assam.gov.in", land: "https://revenueassam.nic.in/ilrms", ration: "https://fcsca.assam.gov.in", igrs: "https://igrassam.gov.in", power: "https://www.apdcl.org", labour: "https://labour.assam.gov.in", agri: "https://diragri.assam.gov.in" },
  br: { edistrict: "https://serviceonline.bihar.gov.in", land: "https://biharbhumi.bihar.gov.in", ration: "https://epds.bihar.gov.in", igrs: "https://bhumijankari.bihar.gov.in", power: "https://nbpdcl.co.in", scholarship: "https://medhasoft.bih.nic.in", labour: "https://bocw.bihar.gov.in", agri: "https://dbtagriculture.bihar.gov.in" },
  cg: { edistrict: "https://edistrict.cgstate.gov.in", land: "https://bhuiyan.cg.nic.in", ration: "https://khadya.cg.nic.in", igrs: "https://epanjeeyan.cg.nic.in", power: "https://cspdcl.co.in", labour: "https://cglabour.nic.in", agri: "https://agriportal.cg.nic.in" },
  ga: { edistrict: "https://goaonline.gov.in", land: "https://egov.goa.nic.in/dslr", ration: "https://goacivilsupplies.gov.in", igrs: "https://ncsgoa.gov.in", power: "https://goaelectricity.gov.in", agri: "https://agri.goa.gov.in" },
  gj: { edistrict: "https://www.digitalgujarat.gov.in", land: "https://anyror.gujarat.gov.in", ration: "https://dcs-dof.gujarat.gov.in", igrs: "https://garvi.gujarat.gov.in", power: "https://www.mgvcl.com", scholarship: "https://www.digitalgujarat.gov.in", labour: "https://sanman.gujarat.gov.in", agri: "https://ikhedut.gujarat.gov.in" },
  hr: { edistrict: "https://saralharyana.gov.in", land: "https://jamabandi.nic.in", ration: "https://haryanafood.gov.in", igrs: "https://jamabandi.nic.in", power: "https://www.dhbvn.org.in", scholarship: "https://harchhatravratti.highereduhry.ac.in", labour: "https://hrylabour.gov.in", agri: "https://fasal.haryana.gov.in" },
  hp: { edistrict: "https://edistrict.hp.gov.in", land: "https://himbhoomi.nic.in", ration: "https://epds.co.in", igrs: "https://hproers.nic.in", power: "https://hpseb.in", labour: "https://hplabourcommissioner.hp.gov.in", agri: "https://hpagrisnet.gov.in" },
  jh: { edistrict: "https://jharsewa.jharkhand.gov.in", land: "https://jharbhoomi.jharkhand.gov.in", ration: "https://aahar.jharkhand.gov.in", igrs: "https://regd.jharkhand.gov.in", power: "https://jbvnl.co.in", scholarship: "https://ekalyan.cgg.gov.in", labour: "https://shramadhan.jharkhand.gov.in", agri: "https://jrfry.jharkhand.gov.in" },
  ka: { edistrict: "https://sevasindhuservices.karnataka.gov.in", land: "https://landrecords.karnataka.gov.in", ration: "https://ahara.kar.nic.in", igrs: "https://kaverionline.karnataka.gov.in", power: "https://bescom.karnataka.gov.in", scholarship: "https://ssp.karnataka.gov.in", labour: "https://karmikaspandana.karnataka.gov.in", agri: "https://fruitspmk.karnataka.gov.in" },
  kl: { edistrict: "https://edistrict.kerala.gov.in", land: "https://erekha.kerala.gov.in", ration: "https://civilsupplieskerala.gov.in", igrs: "https://registration.kerala.gov.in", power: "https://wss.kseb.in", scholarship: "https://dcescholarship.kerala.gov.in", labour: "https://bocwwbkerala.in", agri: "https://aims.kerala.gov.in" },
  mp: { edistrict: "https://mpedistrict.gov.in", land: "https://mpbhulekh.gov.in", ration: "https://rationmitra.nic.in", igrs: "https://www.mpigr.gov.in", power: "https://portal.mpcz.in", scholarship: "https://scholarshipportal.mp.nic.in", labour: "https://labour.mp.gov.in", agri: "https://mpkrishi.mp.gov.in" },
  mh: { edistrict: "https://aaplesarkar.mahaonline.gov.in", land: "https://bhulekh.mahabhumi.gov.in", ration: "https://mahafood.gov.in", igrs: "https://igrmaharashtra.gov.in", power: "https://www.mahadiscom.in", scholarship: "https://mahadbt.maharashtra.gov.in", labour: "https://mahabocw.in", agri: "https://krishi.maharashtra.gov.in" },
  mn: { edistrict: "https://manipuronline.gov.in", ration: "https://epdsmanipur.nic.in", power: "https://mspdcl.com" },
  ml: { edistrict: "https://meghalayaonline.gov.in", ration: "https://megfcsca.gov.in", power: "https://meecl.nic.in" },
  mz: { edistrict: "https://eservices.mizoram.gov.in", ration: "https://fcsca.mizoram.gov.in", power: "https://power.mizoram.gov.in" },
  nl: { edistrict: "https://edistrict.nagaland.gov.in", ration: "https://fcsnagaland.gov.in", power: "https://power.nagaland.gov.in" },
  od: { edistrict: "https://edistrict.odisha.gov.in", land: "https://bhulekh.ori.nic.in", ration: "https://foododisha.in", igrs: "https://igrodisha.gov.in", power: "https://tpcentralodisha.com", scholarship: "https://scholarship.odisha.gov.in", labour: "https://bocboardodisha.in", agri: "https://krushak.odisha.gov.in" },
  pb: { edistrict: "https://eservices.punjab.gov.in", land: "https://jamabandi.punjab.gov.in", ration: "https://foodsuppb.gov.in", igrs: "https://revenue.punjab.gov.in", power: "https://pspcl.in", scholarship: "https://scholarships.punjab.gov.in", labour: "https://pblabour.gov.in", agri: "https://agri.punjab.gov.in" },
  rj: { edistrict: "https://emitra.rajasthan.gov.in", land: "https://apnakhata.rajasthan.gov.in", ration: "https://food.rajasthan.gov.in", igrs: "https://epanjiyan.rajasthan.gov.in", power: "https://www.jdvvnl.com", scholarship: "https://sje.rajasthan.gov.in", labour: "https://labour.rajasthan.gov.in", agri: "https://rajkisan.rajasthan.gov.in" },
  sk: { edistrict: "https://sso.sikkim.gov.in", ration: "https://sikkimfcs-cad.gov.in", power: "https://power.sikkim.gov.in" },
  tn: { edistrict: "https://tnesevai.tn.gov.in", land: "https://eservices.tn.gov.in", ration: "https://www.tnpds.gov.in", igrs: "https://tnreginet.gov.in", power: "https://www.tangedco.gov.in", scholarship: "https://tnesevai.tn.gov.in", labour: "https://labour.tn.gov.in", agri: "https://tnagrisnet.tn.gov.in" },
  tg: { edistrict: "https://ts.meeseva.telangana.gov.in", land: "https://dharani.telangana.gov.in", ration: "https://epds.telangana.gov.in", igrs: "https://registration.telangana.gov.in", power: "https://tgsouthernpower.org", scholarship: "https://telanganaepass.cgg.gov.in", labour: "https://labour.telangana.gov.in", agri: "https://agri.telangana.gov.in" },
  tr: { edistrict: "https://edistrict.tripura.gov.in", ration: "https://fcatripura.gov.in", power: "https://tsecl.co.in" },
  up: { edistrict: "https://edistrict.up.gov.in", land: "https://upbhulekh.gov.in", ration: "https://fcs.up.gov.in", igrs: "https://igrsup.gov.in", power: "https://www.uppcl.org", scholarship: "https://scholarship.up.gov.in", labour: "https://upbocw.in", agri: "https://upagriculture.com" },
  uk: { edistrict: "https://eservices.uk.gov.in", land: "https://bhulekh.uk.gov.in", ration: "https://fcs.uk.gov.in", igrs: "https://registration.uk.gov.in", power: "https://www.upcl.org", scholarship: "https://escholarship.uk.gov.in", labour: "https://uklmis.in", agri: "https://agriculture.uk.gov.in" },
  wb: { edistrict: "https://edistrict.wb.gov.in", land: "https://banglarbhumi.gov.in", ration: "https://wbpds.wb.gov.in", igrs: "https://wbregistration.gov.in", power: "https://www.wbsedcl.in", scholarship: "https://svmcm.wbhed.gov.in", labour: "https://wblabour.gov.in", agri: "https://matirkatha.net" },
  an: { edistrict: "https://edistrict.andaman.gov.in", ration: "https://dcsca.andaman.gov.in", power: "https://apwd.and.nic.in" },
  ch: { edistrict: "https://chandigarh.gov.in", ration: "https://chdfood.gov.in", power: "https://cpdl.co.in" },
  dd: { edistrict: "https://ddd.gov.in", ration: "https://ddd.gov.in", power: "https://ddd.gov.in" },
  dl: { edistrict: "https://edistrict.delhigovt.nic.in", land: "https://dlrc.delhigovt.nic.in", ration: "https://nfs.delhi.gov.in", igrs: "https://revenue.delhi.gov.in", power: "https://www.bsesdelhi.com", scholarship: "https://edistrict.delhigovt.nic.in", labour: "https://labourcis.nic.in", agri: "https://agriculture.delhi.gov.in" },
  jk: { edistrict: "https://eservices.jk.gov.in", land: "https://landrecords.jk.gov.in", ration: "https://jkfcsca.gov.in", power: "https://jkpdd.gov.in" },
  la: { edistrict: "https://ladakh.gov.in", ration: "https://fcsca.ladakh.gov.in", power: "https://ladakh.gov.in" },
  ld: { edistrict: "https://lakshadweep.gov.in", ration: "https://lakshadweep.gov.in", power: "https://lakshadweep.gov.in" },
  py: { edistrict: "https://edistrict.py.gov.in", ration: "https://civilsupply.py.gov.in", power: "https://electricity.py.gov.in", igrs: "https://registration.py.gov.in" },
};

// Which portal each state template should link to.
const TEMPLATE_PORTAL = {
  domicile: "edistrict", caste: "edistrict", income: "edistrict", ews: "edistrict",
  birth: "edistrict", death: "edistrict", marriage: "edistrict", legalheir: "edistrict",
  solvency: "edistrict", udid: "edistrict", seniorcitizen: "edistrict",
  ration: "ration",
  oldage: "edistrict", widow: "edistrict", disability: "edistrict",
  land: "land", mutation: "land", ec: "igrs", propertytax: "ulb", building: "ulb",
  trade: "ulb", shopact: "labour", firenoc: "ulb", labourcard: "labour",
  water: "ulb", electricity: "power",
  prematric: "scholarship", postmatric: "scholarship",
  farmer: "agri",
};

// Hindi titles + optional flags for frequently repeated documents.
const DOC_LIB = {
  "Aadhaar Card": { hi: "आधार कार्ड" },
  "Aadhaar Card of applicant": { hi: "आवेदक का आधार कार्ड" },
  "Aadhaar of applicant": { hi: "आवेदक का आधार कार्ड" },
  "Aadhaar Card and PAN": { hi: "आधार कार्ड और पैन" },
  "Ration card": { hi: "राशन कार्ड" },
  "Ration card or voter ID": { hi: "राशन कार्ड या मतदाता पहचान पत्र" },
  "Address proof": { hi: "पते का प्रमाण" },
  "Domicile proof": { hi: "निवास प्रमाण" },
  "Income proof": { hi: "आय प्रमाण" },
  "Income certificate": { hi: "आय प्रमाण पत्र" },
  "Age proof": { hi: "आयु प्रमाण" },
  "Bank passbook (Aadhaar-linked)": { hi: "आधार से जुड़ी बैंक पासबुक" },
  "Bank passbook": { hi: "बैंक पासबुक" },
  "Passport-size photograph": { hi: "पासपोर्ट साइज़ फोटो" },
  "Passport-size photographs": { hi: "पासपोर्ट साइज़ फोटो" },
  "Two passport-size photographs": { hi: "दो पासपोर्ट साइज़ फोटो" },
  "Photograph": { hi: "फोटो" },
  "Self-declaration": { hi: "स्व-घोषणा", optional: true },
  "Self-declaration / affidavit": { hi: "स्व-घोषणा / शपथ पत्र" },
  "Self-declaration of income": { hi: "आय की स्व-घोषणा" },
  "Death certificate of the deceased": { hi: "मृत्यु प्रमाण पत्र" },
  "Caste / minority certificate": { hi: "जाति / अल्पसंख्यक प्रमाण पत्र" },
  "Sale deed / will / gift deed": { hi: "विक्रय विलेख / वसीयत / दान विलेख" },
  "Mobile number linked with Aadhaar": { hi: "आधार से जुड़ा मोबाइल नंबर" },
  "Mobile linked with Aadhaar": { hi: "आधार से जुड़ा मोबाइल नंबर" },
  "Blood group / medical details (optional)": { hi: "रक्त समूह / चिकित्सा विवरण", optional: true },
  "Valuation report of assets": { hi: "संपत्ति मूल्यांकन रिपोर्ट", optional: true },
  "No-objection from co-owners (if any)": { hi: "सह-मालिकों से अनापत्ति", optional: true },
  "Surrender certificate of previous card (if any)": { hi: "पिछले कार्ड का समर्पण प्रमाण पत्र", optional: true },
  "Partnership deed / incorporation certificate (if applicable)": { hi: "साझेदारी विलेख / निगमन प्रमाण पत्र", optional: true },
  "Soil test report": { hi: "मृदा परीक्षण रिपोर्ट", optional: true },
  "Marriage invitation / photographs": { hi: "विवाह निमंत्रण / तस्वीरें", optional: true },
  "Building completion / occupancy certificate": { hi: "पूर्णता / अधिभोग प्रमाण पत्र", optional: true },
  "Latest electricity bill of neighbour (for reference)": { hi: "पड़ोसी का नवीनतम बिजली बिल", optional: true },
};

// UT-only subset – skip a few state-only services for UTs
const UT_SET = new Set(["an", "ch", "dd", "dl", "jk", "la", "ld", "py"]);
const UT_SKIP = new Set(["building", "trade"]); // optional reduction

const CENTRAL = [
  { slug: "voter-id-epic", cat: "Identity", en: "Voter ID Card (EPIC)", hi: "मतदाता पहचान पत्र", auth: "Election Commission of India", time: "30 days", fee: "Free",
    desc: "Photo identity card issued to eligible Indian citizens for voting in elections.",
    docs: ["Aadhaar / passport / driving licence (age proof)", "Address proof", "Recent photograph", "Form 6"],
    elig: ["Indian citizen aged 18+", "Ordinary resident of the constituency"], url: "https://voters.eci.gov.in" },
  { slug: "voter-id-form-8", cat: "Identity", en: "Voter ID Correction (Form 8)", hi: "मतदाता विवरण सुधार", auth: "Election Commission of India", time: "15–30 days", fee: "Free",
    desc: "Correction of name, address, photograph or shifting of polling station in the electoral roll.",
    docs: ["Existing EPIC", "Document supporting the correction", "Aadhaar"],
    elig: ["Registered voter wishing to update particulars"], url: "https://voters.eci.gov.in" },
  { slug: "digilocker", cat: "Identity", en: "DigiLocker Account", hi: "डिजीलॉकर खाता", auth: "MeitY, Government of India", time: "Instant", fee: "Free",
    desc: "Cloud-based document wallet for storing and sharing Aadhaar-linked verified government documents.",
    docs: ["Aadhaar number", "Mobile linked with Aadhaar"],
    elig: ["Any Indian citizen with Aadhaar"], url: "https://digilocker.gov.in" },
  { slug: "umang", cat: "Identity", en: "UMANG App Registration", hi: "उमंग ऐप पंजीकरण", auth: "MeitY / NeGD", time: "Instant", fee: "Free",
    desc: "Unified mobile platform for 1,700+ central and state government services.",
    docs: ["Mobile number", "Aadhaar (optional for KYC)"],
    elig: ["Any user of central / state government services"], url: "https://web.umang.gov.in" },
  { slug: "mparivahan", cat: "Driving", en: "mParivahan / DigiLocker DL & RC", hi: "एमपरिवहन डीएल/आरसी", auth: "MoRTH", time: "Instant", fee: "Free",
    desc: "Digital driving licence and registration certificate via the mParivahan / DigiLocker apps.",
    docs: ["Driving Licence number", "Vehicle registration number", "DigiLocker / mParivahan account"],
    elig: ["DL / RC holder"], url: "https://parivahan.gov.in" },
  { slug: "international-driving-permit", cat: "Driving", en: "International Driving Permit (IDP)", hi: "अंतर्राष्ट्रीय ड्राइविंग परमिट", auth: "Regional Transport Office", time: "3–7 days", fee: "₹1,000",
    desc: "Permit allowing Indian licence holders to drive in 100+ countries that recognise the 1949 Geneva Convention.",
    docs: ["Valid Indian Driving Licence", "Passport with valid visa", "Air ticket / travel itinerary", "Medical Form 1A", "Application Form 4A"],
    elig: ["Holder of a valid Indian driving licence aged 18+"], url: "https://parivahan.gov.in" },
  { slug: "learners-licence", cat: "Driving", en: "Learner's Licence", hi: "लर्नर लाइसेंस", auth: "Regional Transport Office", time: "Same day", fee: "₹200",
    desc: "Provisional licence allowing a learner to drive under supervision before applying for a permanent DL.",
    docs: ["Aadhaar / address proof", "Age proof", "Passport-size photograph", "Form 1 (medical self-declaration)"],
    elig: ["Aged 16+ for gearless two-wheelers (≤50cc), 18+ for other vehicles"], url: "https://parivahan.gov.in" },
  { slug: "vehicle-fitness-certificate", cat: "Driving", en: "Vehicle Fitness Certificate", hi: "वाहन फिटनेस प्रमाण पत्र", auth: "Regional Transport Office", time: "1–7 days", fee: "₹200–₹600",
    desc: "Mandatory certificate certifying that a commercial / transport vehicle is roadworthy.",
    docs: ["Registration Certificate (RC)", "Valid insurance", "Valid PUC", "Form 38 application"],
    elig: ["Owner of a commercial / transport vehicle due for fitness inspection"], url: "https://parivahan.gov.in" },
  { slug: "high-security-number-plate", cat: "Driving", en: "High Security Number Plate", hi: "हाई सिक्योरिटी नंबर प्लेट", auth: "MoRTH / State RTO", time: "15–30 days", fee: "₹500–₹1,100",
    desc: "Tamper-proof number plate mandatory for all motor vehicles in India.",
    docs: ["Vehicle RC", "Chassis & engine number", "Owner's contact details"],
    elig: ["Owner of any registered motor vehicle"], url: "https://bookmyhsrp.com" },
  { slug: "passport-tatkaal", cat: "Travel", en: "Passport (Tatkaal)", hi: "तत्काल पासपोर्ट", auth: "Ministry of External Affairs", time: "3–7 days", fee: "₹3,500 + ₹2,000 Tatkaal",
    desc: "Expedited issuance of Indian passport for urgent travel needs.",
    docs: ["Aadhaar / Voter ID / PAN", "Address proof", "Date of birth proof", "Standard affidavit (Annexure F)"],
    elig: ["Indian citizen needing urgent passport"], url: "https://www.passportindia.gov.in" },
  { slug: "oci-card", cat: "Travel", en: "OCI Card", hi: "ओसीआई कार्ड", auth: "Ministry of Home Affairs", time: "30–90 days", fee: "USD 275 / equivalent",
    desc: "Overseas Citizen of India card providing lifelong multi-entry visa for persons of Indian origin.",
    docs: ["Foreign passport", "Proof of Indian origin (old Indian passport / parents' passport)", "Recent photograph", "Renunciation certificate (if applicable)"],
    elig: ["Foreign national who was, or whose ancestors were, Indian citizens"], url: "https://ociservices.gov.in" },
  { slug: "pcc-passport", cat: "Travel", en: "Police Clearance Certificate (PCC)", hi: "पुलिस सत्यापन प्रमाण पत्र", auth: "Ministry of External Affairs", time: "7–14 days", fee: "₹500",
    desc: "Certificate confirming no criminal record, required for employment, visa or long-term stay abroad.",
    docs: ["Original passport", "Address proof", "Purpose-of-PCC document (job offer, visa form)"],
    elig: ["Indian passport holder applying for an overseas opportunity"], url: "https://www.passportindia.gov.in" },
  { slug: "evisa-india", cat: "Travel", en: "Indian e-Visa (for foreigners)", hi: "भारतीय ई-वीज़ा", auth: "Bureau of Immigration, MHA", time: "3–5 days", fee: "USD 25–80",
    desc: "Online visa for foreign nationals visiting India for tourism, business, medical or conference purposes.",
    docs: ["Scanned passport bio-page", "Recent passport photograph", "Return ticket / itinerary"],
    elig: ["Foreign national from an e-Visa eligible country"], url: "https://indianvisaonline.gov.in/evisa" },
  { slug: "gst-registration", cat: "Finance", en: "GST Registration", hi: "जीएसटी पंजीकरण", auth: "Goods & Services Tax Network", time: "3–7 days", fee: "Free",
    desc: "Goods and Services Tax registration mandatory for businesses crossing the prescribed turnover threshold.",
    docs: ["PAN of business / proprietor", "Aadhaar", "Proof of business address", "Bank account details", "Photograph", "Constitution proof (partnership / incorporation)"],
    elig: ["Business with turnover above the GST threshold", "Inter-state suppliers and e-commerce sellers (regardless of turnover)"], url: "https://www.gst.gov.in" },
  { slug: "udyam-msme", cat: "Finance", en: "Udyam (MSME) Registration", hi: "उद्यम पंजीकरण", auth: "Ministry of MSME", time: "Instant", fee: "Free",
    desc: "Free online registration for Micro, Small and Medium Enterprises with permanent Udyam Registration Number.",
    docs: ["Aadhaar of proprietor / partner / director", "PAN of enterprise", "GSTIN (if applicable)"],
    elig: ["Any enterprise within MSME investment & turnover limits"], url: "https://udyamregistration.gov.in" },
  { slug: "fssai-licence", cat: "Finance", en: "FSSAI Food Licence", hi: "एफएसएसएआई लाइसेंस", auth: "Food Safety & Standards Authority of India", time: "30–60 days", fee: "₹100–₹7,500 per year",
    desc: "Mandatory licence / registration for any food business operator in India.",
    docs: ["PAN / Aadhaar", "Proof of business premises", "Food safety management plan", "List of food categories", "Photograph"],
    elig: ["Any FBO – manufacturer, processor, distributor, retailer or transporter of food"], url: "https://foscos.fssai.gov.in" },
  { slug: "iec-code", cat: "Finance", en: "Import Export Code (IEC)", hi: "आयात-निर्यात कोड", auth: "DGFT, Ministry of Commerce", time: "3–7 days", fee: "₹500",
    desc: "10-digit code mandatory for businesses engaged in import or export from India.",
    docs: ["PAN of business", "Aadhaar of proprietor / partner", "Bank certificate / cancelled cheque", "Address proof"],
    elig: ["Any person / firm planning to import or export"], url: "https://dgft.gov.in" },
  { slug: "trademark-registration", cat: "Finance", en: "Trademark Registration", hi: "ट्रेडमार्क पंजीकरण", auth: "Office of the Controller General of Patents, Designs & Trademarks", time: "12–24 months", fee: "₹4,500–₹9,000 per class",
    desc: "Statutory protection of a brand name, logo or slogan under the Trade Marks Act, 1999.",
    docs: ["Logo / wordmark", "Applicant identity & address proof", "Power of attorney (Form TM-48)", "User affidavit (if prior use claimed)"],
    elig: ["Any individual, company, LLP or proprietorship using a mark in trade"], url: "https://ipindia.gov.in" },
  { slug: "patent-registration", cat: "Finance", en: "Patent Registration", hi: "पेटेंट पंजीकरण", auth: "Indian Patent Office", time: "24–48 months", fee: "₹1,600+",
    desc: "Exclusive rights for an invention that is new, involves an inventive step and is industrially applicable.",
    docs: ["Patent specification (provisional / complete)", "Form 1, 2, 3, 5", "Inventor declaration", "Power of authority (if filed via agent)"],
    elig: ["True and first inventor or assignee"], url: "https://ipindia.gov.in" },
  { slug: "itr-filing", cat: "Finance", en: "Income Tax Return (ITR) Filing", hi: "आयकर रिटर्न दाखिल", auth: "Income Tax Department", time: "Instant filing; refund 30–60 days", fee: "Free",
    desc: "Annual filing of income tax return for individuals, HUFs and businesses.",
    docs: ["PAN & Aadhaar", "Form 16 / 16A", "Bank statements & interest certificates", "Capital gains statements", "Proof of deductions (80C, 80D, etc.)"],
    elig: ["Any person whose income exceeds the basic exemption limit or who needs to claim refund / carry forward losses"], url: "https://www.incometax.gov.in" },
  { slug: "tan-application", cat: "Finance", en: "TAN Application", hi: "टैन आवेदन", auth: "Income Tax Department / Protean", time: "7 days", fee: "₹65",
    desc: "Tax Deduction and Collection Account Number for deductors of TDS / TCS.",
    docs: ["Form 49B", "Identity proof of applicant", "Address proof"],
    elig: ["Any person required to deduct or collect tax at source"], url: "https://www.protean-tinpan.com" },
  { slug: "pm-kisan", cat: "Welfare", en: "PM Kisan Samman Nidhi", hi: "पीएम किसान सम्मान निधि", auth: "Ministry of Agriculture & Farmers Welfare", time: "30–60 days", fee: "Free",
    desc: "₹6,000 per year direct income support to all landholding farmer families across India.",
    docs: ["Aadhaar", "Land ownership records", "Bank account (Aadhaar-linked)"],
    elig: ["Landholding farmer family", "Not falling under exclusion criteria (high-income, government employee, etc.)"], url: "https://pmkisan.gov.in" },
  { slug: "kisan-credit-card", cat: "Welfare", en: "Kisan Credit Card", hi: "किसान क्रेडिट कार्ड", auth: "NABARD / Public Sector Banks", time: "15–30 days", fee: "Nominal",
    desc: "Short-term credit at subsidised interest for crop production, allied activities and household needs of farmers.",
    docs: ["Aadhaar", "Land records / lease document", "Bank passbook", "Photograph"],
    elig: ["Farmer (owner / tenant / share-cropper) including SHG / JLG members"], url: "https://www.nabard.org" },
  { slug: "soil-health-card", cat: "Welfare", en: "Soil Health Card", hi: "मृदा स्वास्थ्य कार्ड", auth: "Ministry of Agriculture", time: "30 days", fee: "Free",
    desc: "Crop-wise soil nutrient status and fertiliser recommendations for farmers' plots.",
    docs: ["Aadhaar", "Land records", "Soil sample (collected with agri-officer)"],
    elig: ["Farmer owning / cultivating land"], url: "https://soilhealth.dac.gov.in" },
  { slug: "pmay-urban", cat: "Welfare", en: "PM Awas Yojana – Urban", hi: "प्रधानमंत्री आवास योजना (शहरी)", auth: "Ministry of Housing & Urban Affairs", time: "60–120 days", fee: "Free",
    desc: "Interest subsidy and affordable housing for EWS / LIG / MIG families in urban areas.",
    docs: ["Aadhaar of all family members", "Income proof", "Existing house affidavit", "Bank account details"],
    elig: ["Family with no pucca house in India", "Annual income within EWS / LIG / MIG ceilings"], url: "https://pmaymis.gov.in" },
  { slug: "pmay-gramin", cat: "Welfare", en: "PM Awas Yojana – Gramin", hi: "प्रधानमंत्री आवास योजना (ग्रामीण)", auth: "Ministry of Rural Development", time: "90–180 days", fee: "Free",
    desc: "Financial assistance for construction of pucca houses for rural BPL households.",
    docs: ["Aadhaar", "SECC 2011 reference", "Bank account", "MGNREGA job card"],
    elig: ["Houseless / inadequate-housing rural family identified under SECC"], url: "https://pmayg.nic.in" },
  { slug: "ayushman-bharat", cat: "Welfare", en: "Ayushman Bharat PMJAY Card", hi: "आयुष्मान भारत कार्ड", auth: "National Health Authority", time: "Instant–7 days", fee: "Free",
    desc: "₹5 lakh per family per year health insurance for secondary and tertiary care hospitalisation.",
    docs: ["Aadhaar", "Ration card / SECC reference", "Mobile number"],
    elig: ["Family identified under SECC 2011 deprivation criteria or state-specified extension lists"], url: "https://pmjay.gov.in" },
  { slug: "ujjwala-lpg", cat: "Welfare", en: "PM Ujjwala LPG Connection", hi: "उज्ज्वला एलपीजी कनेक्शन", auth: "Ministry of Petroleum & Natural Gas", time: "7–15 days", fee: "Free deposit",
    desc: "Free LPG connection with deposit-free cylinder and first refill for women from BPL households.",
    docs: ["Aadhaar of applicant (woman)", "Ration card / SECC reference", "Bank account", "Address proof"],
    elig: ["Adult woman from BPL / Antyodaya family with no existing LPG connection"], url: "https://pmuy.gov.in" },
  { slug: "atal-pension-yojana", cat: "Finance", en: "Atal Pension Yojana", hi: "अटल पेंशन योजना", auth: "PFRDA", time: "Instant", fee: "Auto-debit contribution",
    desc: "Guaranteed monthly pension of ₹1,000–₹5,000 from age 60 for unorganised sector workers.",
    docs: ["Aadhaar", "Bank / post-office account", "Mobile number"],
    elig: ["Indian citizen aged 18–40 with a savings account"], url: "https://npscra.nsdl.co.in/scheme-details.php" },
  { slug: "nps-account", cat: "Finance", en: "National Pension System (NPS) Account", hi: "एनपीएस खाता", auth: "PFRDA", time: "1–3 days", fee: "Variable charges",
    desc: "Voluntary, defined-contribution retirement savings scheme regulated by PFRDA.",
    docs: ["Aadhaar / PAN", "Bank details", "Photograph", "FATCA self-certification"],
    elig: ["Indian citizen aged 18–70"], url: "https://enps.nsdl.com" },
  { slug: "epfo-uan", cat: "Finance", en: "EPFO UAN Activation", hi: "ईपीएफओ यूएएन सक्रियण", auth: "Employees' Provident Fund Organisation", time: "Instant", fee: "Free",
    desc: "Universal Account Number activation for EPF members for online passbook, claims and transfers.",
    docs: ["UAN", "Aadhaar", "PAN", "Bank account", "Mobile number"],
    elig: ["EPF member (current or past) with allotted UAN"], url: "https://unifiedportal-mem.epfindia.gov.in" },
  { slug: "esic-registration", cat: "Finance", en: "ESIC Employer Registration", hi: "ईएसआईसी पंजीकरण", auth: "Employees' State Insurance Corporation", time: "15 days", fee: "Free",
    desc: "Mandatory registration for establishments with 10+ employees earning up to ₹21,000/month.",
    docs: ["PAN of establishment", "Address proof", "List of employees with salary", "Bank details", "Constitution document"],
    elig: ["Factory / establishment covered under the ESI Act"], url: "https://www.esic.gov.in" },
  { slug: "sukanya-samriddhi", cat: "Finance", en: "Sukanya Samriddhi Yojana", hi: "सुकन्या समृद्धि योजना", auth: "Ministry of Finance / India Post", time: "Same day", fee: "Free (min ₹250 deposit)",
    desc: "Small savings scheme for the girl child offering high interest and tax benefits under 80C.",
    docs: ["Birth certificate of girl child", "Parent / guardian Aadhaar & PAN", "Address proof"],
    elig: ["Girl child below 10 years of age", "Account opened by parent / legal guardian"], url: "https://www.indiapost.gov.in" },
  { slug: "pmsby", cat: "Finance", en: "PM Suraksha Bima Yojana", hi: "पीएम सुरक्षा बीमा योजना", auth: "Ministry of Finance", time: "Instant", fee: "₹20 per year",
    desc: "₹2 lakh accidental death and disability cover for ages 18–70 with savings account.",
    docs: ["Aadhaar-linked savings account", "Mobile number"],
    elig: ["Account holder aged 18–70 with valid Aadhaar"], url: "https://jansuraksha.gov.in" },
  { slug: "pmjjby", cat: "Finance", en: "PM Jeevan Jyoti Bima Yojana", hi: "पीएम जीवन ज्योति बीमा योजना", auth: "Ministry of Finance", time: "Instant", fee: "₹436 per year",
    desc: "₹2 lakh life cover for ages 18–50 holding a savings bank account.",
    docs: ["Aadhaar-linked savings account", "Mobile number", "Good health declaration"],
    elig: ["Account holder aged 18–50"], url: "https://jansuraksha.gov.in" },
  { slug: "eshram-card", cat: "Welfare", en: "e-Shram Card", hi: "ई-श्रम कार्ड", auth: "Ministry of Labour & Employment", time: "Instant", fee: "Free",
    desc: "Universal Account Number card for unorganised workers giving access to social security benefits.",
    docs: ["Aadhaar", "Mobile number linked with Aadhaar", "Bank account"],
    elig: ["Unorganised worker aged 16–59 not paying EPF / ESI"], url: "https://eshram.gov.in" },
  { slug: "neet-ug", cat: "Education", en: "NEET (UG) Registration", hi: "नीट यूजी पंजीकरण", auth: "National Testing Agency", time: "Annual cycle", fee: "₹1,700 (General)",
    desc: "National Eligibility cum Entrance Test for admission to MBBS / BDS / AYUSH programmes.",
    docs: ["Aadhaar / valid ID", "Class 10 & 12 mark sheets", "Recent photograph", "Signature"],
    elig: ["Class 12 with Physics, Chemistry, Biology", "Minimum age 17 at admission"], url: "https://neet.nta.nic.in" },
  { slug: "jee-main", cat: "Education", en: "JEE Main Registration", hi: "जेईई मेन पंजीकरण", auth: "National Testing Agency", time: "Annual cycle", fee: "₹1,000 (General)",
    desc: "Common entrance test for NITs, IIITs, CFTIs and screening for JEE Advanced.",
    docs: ["Aadhaar / valid ID", "Class 10 & 12 mark sheets", "Recent photograph", "Signature"],
    elig: ["Passed / appearing class 12 with PCM / PCB"], url: "https://jeemain.nta.nic.in" },
  { slug: "ugc-net", cat: "Education", en: "UGC NET Registration", hi: "यूजीसी नेट पंजीकरण", auth: "National Testing Agency", time: "Bi-annual cycle", fee: "₹1,150 (General)",
    desc: "National Eligibility Test for Assistant Professorship / JRF in Indian universities.",
    docs: ["Master's degree mark sheet", "Aadhaar / valid ID", "Photograph & signature"],
    elig: ["Master's degree with 55% (50% for reserved categories)"], url: "https://ugcnet.nta.nic.in" },
  { slug: "arms-licence", cat: "Identity", en: "Arms Licence", hi: "आर्म्स लाइसेंस", auth: "District Magistrate / MHA", time: "60–180 days", fee: "Per category",
    desc: "Licence under the Arms Act, 1959 for possession of firearms for self-defence, sport or crop protection.",
    docs: ["Aadhaar / ID & address proof", "Character certificate", "Medical fitness certificate", "Reason for need (threat perception)", "Photograph"],
    elig: ["Adult Indian citizen with no criminal antecedents", "Justified necessity"], url: "https://ndal-alis.gov.in" },
  { slug: "cdc-seafarer", cat: "Travel", en: "Continuous Discharge Certificate (CDC)", hi: "सीडीसी (सीफरर बुक)", auth: "Directorate General of Shipping", time: "30–60 days", fee: "₹400",
    desc: "Mandatory service book and ID for Indian seafarers working on merchant ships.",
    docs: ["Indian passport", "Pre-sea training certificate (DGS approved)", "Medical fitness certificate", "Photograph"],
    elig: ["Indian citizen aged 18+ trained for merchant marine service"], url: "https://www.dgshipping.gov.in" },
  { slug: "dgca-cpl", cat: "Travel", en: "DGCA Commercial Pilot Licence", hi: "डीजीसीए सीपीएल", auth: "Directorate General of Civil Aviation", time: "60–120 days", fee: "Varies",
    desc: "Licence permitting holders to act as pilot-in-command of aircraft engaged in commercial operations.",
    docs: ["Class I medical certificate", "Flying hours log book", "Training school certificates", "DGCA written exam pass certificates"],
    elig: ["Aged 18+", "Minimum 200 flying hours and required medical class"], url: "https://www.dgca.gov.in" },
  { slug: "pf-withdrawal", cat: "Finance", en: "EPF Withdrawal / Transfer Claim", hi: "पीएफ निकासी / ट्रांसफर", auth: "EPFO", time: "10–20 days", fee: "Free",
    desc: "Online claim (Form 19 / 10C / 31) for final settlement, pension or partial withdrawal of EPF.",
    docs: ["UAN with KYC complete", "Aadhaar-linked bank account", "PAN (for tax)"],
    elig: ["EPF member with active UAN and seeded KYC"], url: "https://unifiedportal-mem.epfindia.gov.in" },
  { slug: "income-tax-pan-correction", cat: "Finance", en: "PAN Correction / Reprint", hi: "पैन सुधार / पुनर्मुद्रण", auth: "Income Tax Department / Protean", time: "7–15 days", fee: "₹50–₹110",
    desc: "Update name, DOB, photograph or address on PAN, or get a reprinted PAN card.",
    docs: ["Existing PAN", "Supporting proof for correction", "Aadhaar"],
    elig: ["Existing PAN holder"], url: "https://www.onlineservices.nsdl.com" },
  { slug: "aadhaar-update", cat: "Identity", en: "Aadhaar Address / Mobile Update", hi: "आधार अपडेट", auth: "UIDAI", time: "7–30 days", fee: "₹50",
    desc: "Update of name, address, mobile number, photograph or biometrics in Aadhaar.",
    docs: ["Existing Aadhaar", "Document supporting the change"],
    elig: ["Aadhaar holder"], url: "https://myaadhaar.uidai.gov.in" },
  { slug: "csc-vle", cat: "Welfare", en: "CSC VLE Registration", hi: "सीएससी वीएलई पंजीकरण", auth: "CSC e-Governance Services India", time: "30–60 days", fee: "Free",
    desc: "Registration as Village Level Entrepreneur to operate a Common Service Centre delivering G2C services.",
    docs: ["Aadhaar", "PAN", "Educational certificates (class 10+)", "Address proof", "Bank account"],
    elig: ["Indian citizen aged 18+ with basic IT proficiency"], url: "https://register.csc.gov.in" },
];

const toSlug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const j = (a) => JSON.stringify(a);
const txt = (s) => JSON.stringify(s);

const out = [];
out.push(`// AUTO-GENERATED by scripts/gen-catalog.mjs – do not edit by hand.`);
out.push(`import type { GovService } from "./services-data";\n`);
out.push(`const baseDocs = [`);
out.push(`  { title: { en: "Aadhaar Card", hi: "आधार कार्ड" }, required: true },`);
out.push(`  { title: { en: "Recent passport-size photograph", hi: "पासपोर्ट साइज़ फोटो" }, required: true },`);
out.push(`];\n`);
out.push(`export const catalogServices: GovService[] = [`);

// Central
for (const c of CENTRAL) {
  const docs = c.docs.map(d => `    { title: { en: ${txt(d)}, hi: "" }, required: true },`).join("\n");
  out.push(`  {
    slug: ${txt(c.slug)},
    name: { en: ${txt(c.en)}, hi: ${txt(c.hi)} },
    category: ${txt(c.cat)},
    authority: ${txt(c.auth)},
    processingTime: ${txt(c.time)},
    fee: ${txt(c.fee)},
    description: { en: ${txt(c.desc)}, hi: ${txt(c.desc)} },
    documents: [
${docs}
    ],
    eligibility: { en: ${j(c.elig)}, hi: ${j(c.elig)} },
    applyUrl: ${txt(c.url)},
  },`);
}

// State
for (const [stateName, code, url] of STATES) {
  const isUT = UT_SET.has(code);
  for (const t of STATE_TEMPLATES) {
    if (isUT && UT_SKIP.has(t.key)) continue;
    const slug = `${code}-${t.key}`;
    const en = t.en;
    const desc = t.desc.replace(/\{state\}/g, stateName);
    const elig = t.elig.map(e => e.replace(/\{state\}/g, stateName));
    const docs = t.docs.map(d => `    { title: { en: ${txt(d)}, hi: "" }, required: true },`).join("\n");
    out.push(`  {
    slug: ${txt(slug)},
    name: { en: ${txt(en)}, hi: ${txt(t.hi)} },
    category: ${txt(t.cat)},
    authority: ${txt(t.auth)},
    state: ${txt(stateName)},
    processingTime: ${txt(t.time)},
    fee: ${txt(t.fee)},
    description: { en: ${txt(desc)}, hi: ${txt(desc)} },
    documents: [
${docs}
    ],
    eligibility: { en: ${j(elig)}, hi: ${j(elig)} },
    applyUrl: ${txt(url)},
  },`);
  }
}

out.push(`];`);

writeFileSync("src/lib/services-catalog.ts", out.join("\n"));
console.log("Wrote src/lib/services-catalog.ts with",
  CENTRAL.length + STATES.reduce((n,[,c]) => n + (UT_SET.has(c) ? STATE_TEMPLATES.length - UT_SKIP.size : STATE_TEMPLATES.length), 0),
  "entries");
